### ISSUE TITLE
Checker for the RHS of a "if foo in [1, 2, 3]" expression

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#1001]
I noticed the RHS type of something like `if foo in ['one', 'two']:` has grown pretty inconsistent in my project:
- `if foo in ['one', 'two']:`
- `if foo in ('one', 'two'):`
- `if foo in {'one', 'two'}:`

I'd like to consistently enforce one type (probably lists). Do you think it'd make sense to add a checker like this to the pylint core, or should I try to write a local extension module?

**Comment by PCManticore** [comment]
I don't understand how would it work? Inspecting all contain checks from a module and learn from it or hard code one and emit about the others? I think it is kind of specialized, I'm not sure how fitting would it be for core or for extensions.

I would use sets by the way, should be O(1).

**Comment by The-Compiler** [comment]
I'd imagine you configure something like `constant-comparison-iterable-type = list` and if you do so, that's enforced (without the config, the checker is just silent)

> I would use sets by the way, should be O(1).

That seems like micro-optimizing :wink: I settled on lists, as that's what people seem to be most used to. FWIW, pylint and astroid seem to use tuples and some lists in their code (grep for `' in [[{(]'`)

**Comment by PCManticore** [comment]
Okay, in this case, if you are willing to make an extension, I'll be happy to include it. It could prove useful.

**Comment by The-Compiler** [comment]
I'd give it a try - can you give me a quick overview of what nodes I'd need to visit? I still know like nothing about astroid and Python ASTs :wink:

I guess I'd need to visit some `in` node, then not infer the RHS (as I only want to check constants), and then somehow check the type of that?

**Comment by PCManticore** [comment]
Sure!

You will have to visit the Compare node. It has two attributes, ``.left`` and ``.ops``, where the .ops will be a tuple of operands and objects to compare with. In this case, you just have to check if the operand is ``in`` and the right hand side is a literal. I presume we should limit this to ``x in {...}`` rather than ``x in z``, where ``z`` is a name, but this depends on you mostly. By checking if it is a literal, you just need to check if it is a astroid.Set, astroid.List, astroid.Tuple or maybe Dict, otherwise, just .infer() the node and see the result of the inference if it is what you need.

Let me know how things go.

**Comment by rogalski** [comment]
I'd vote to close it as 'will not implement'. Seems like a too much of a nitpick to be included in Pylint core.

**Comment by PCManticore** [comment]
Sorry @The-Compiler :-)

**Comment by The-Compiler** [comment]
No worries - I might write this myself one day, but there's always more ideas than time :wink:
