### ISSUE TITLE
Add a more comprehensive checker documentation

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1071]
Check https://docs.pylint.org/en/latest/custom_checkers.html#writing-your-own-checker

**Comment by iselind** [comment]
The importance of the implements line is not highlighted at all.

Bullet two concerning priority. How checkers are ordered (internally?) doesn't help me to decide if i should set a negative priority close to zero or very far from zero in order for the checker to be first or at least among the first.

I interpret this page as a resource you'd give programmers new to pylint checkers to get them started, awesome start! I think it would be really helpful if the page gave a overview of how the AST is buid and how i'm meant to access for example function variables in a function or the identifiers defined in a module. Where can i find a list of all the visit_* methods that i can use? I cannot find any class defining them all, are they dynamically called somehow?

In examples directory referred to, looking at custom_raw.py. It implements process_module() instead of visit_*. What is the difference? When should i choose one over the other?
