### ISSUE TITLE
False negative R0204 (redefined-variable-type)

### ISSUE THREAD

**Issue by zweissman** [PyCQA/pylint#1114]
I am trying to change the value of a variable from one value in an Enum to another in the same Enum and it warns that I am redefining the variable.

Code:
DataUtils/Enums.py
from enum import IntEnum, Enum

class InstrumentRequestCode(IntEnum):
    Success = 0
    RequestNotFound = 1
    UnknownHeader = 2
    UnknownTableFormat = 3
    FailsDataValidation = 4

Main.py
request_code = InstrumentRequestCode.Success

if [conditional]:
    request_code = InstrumentRequestCode.RequestNotFound

### Current behavior
Warning		Redefinition of request_code type from DataUtils.Enums.InstrumentRequestCode.Success to DataUtils.Enums.InstrumentRequestCode.RequestNotFound [R:redefined-variable-type]

### Expected behavior
Should not be an issue, they are both of the same enum type DataUtils.Enums.InstrumentRequestCode

### pylint --version output
pylint 1.6.4,
astroid 1.4.8
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

**Comment by PCManticore** [comment]
Thank you for reporting this issue. You are right, we do have plenty of problems with this error message. Due to these limitations, the error check actually was moved into a separate extension in Pylint 2.0, meaning it will warn about these cases only when the user enables it, so feel free to ignore it altogether for now.

**Comment by PCManticore** [comment]
Closing for now. Probably we will scrap the error altogether at some point.
