### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#118]
Originally reported by: **James Broadhead (BitBucket: [jamesbroadhead](http://bitbucket.org/jamesbroadhead), GitHub: @jamesbroadhead?)**

----------------------------------------

Please pin the dependencies of pylint, so that two developers installing a pinned version of pylint at different times always receive consistent output. 
http://nvie.com/posts/pin-your-packages/

This has a serious impact on teams who want to use pylint for CI. 

eg. Project pins pylint-1.0.0 in requirements.txt (does not list astroid, since it's not a direct dependency) 
Dev1 installs pylint via pip install -r requirements.txt, gets version X of astroid
Later, Dev2 installs pylint via pip install -r requirements.txt, gets version X+1 of astroid
Version X+1 detects new error types over X. Rather than a consistent, planned upgrade to astroid-X+1, either Dev2 must manually downgrade and remember not to upgrade by accident, or the whole team + CI must upgrade to the later version as soon as this situation occurs. 

With pinned deps, the whole team could note that a new version of astroid was released, and a new version of pylint, pinned to the newer astroid. In a planned manner, they could upgrade tooling and their requirements.txt. 

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/118

**Comment by PCManticore** [comment]
Closing this issue. Unfortunately we cannot make the commitment of having only bug fixes on minor versions, since even fixing a false positive can not be necessarily considered a bug fix. The pinning can be done at the level of each individual team. We also employ some pinning though, between the current minor release version (1.X) and the one that's being developed next (1.X + 1).

**Comment by jamesbroadhead** [comment]
This bug report is not about maintaining consistency between minor/major versions of pylint. It is about maintaining consistent behaviour in *the same* version of pylint. 

It is about version pinning each release of pylint to a specific version of astroid, so that two developers running `pip install -r requirements.txt`, where the requirements.txt file lists a specific version of pylint get consistent beheviour.
