### ISSUE TITLE
pylint reports that pyodbc.connect method does not exist

### ISSUE THREAD

**Issue by gbritton1** [PyCQA/pylint#1209]
### Steps to reproduce
1. install pyodbc
2. try to use the pyodbc.connect method
3. 

### Current behavior

Pylint reports Module 'pyodbc' has no 'connect' member

### Expected behavior

Pylint reports no error

### pylint --version output

pylint 1.6.4,
astroid 1.4.8
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (In
tel)]

Reference: [https://github.com/mkleehammer/pyodbc/issues/115](url)

**Comment by PCManticore** [comment]
pyodbc seems to be an extension package. Can you try running pylint with ``--extension-pkg-whitelist=pyodbc``?

**Comment by gbritton1** [comment]
Yes that works but why can't pylint find the method? Put another way, what
can the pyodbc team do to make it work with pylint?

**Comment by PCManticore** [comment]
Okay, perfect!

Not familiar with pyodbc's code base, but from a quick glance, it seems to be a C extension. This puts pylint into a tough situation, since it needs to be able to parse the code into ASTs and use those trees for generating objects that can be internally interpreted. In this case, without having access to a source code, pylint can import the respective module and build some kind of ASTs objects on top of that. This is of course a security risk and we shouldn't do this blindly, an extension might be malformed, might take a lot of resources at import time or any other weird scenario you can imagine, hence the use of ``--extension-pkg-whitelist`` to specify to pylint that it can include your module for a deep analysis without worrying too much about security.

Now you might now like using this. As an alternative, we do support providing some hints to pylint, through https://github.com/PyCQA/astroid/tree/master/astroid/brain, in which we can say how a particular module or class can look like. It's basically like a stub, but on steroids, since you have access to the entire tree and inference API when building the stub. This might be another way of improving the situation for pyodbc for instance, by providing such a stub, through which pylint can know how the API of pyodbc looks like.
In the future, we will also support PEP 484 stubs, so that will be definitely easier and more straight forward to do.

**Comment by gbritton1** [comment]
I like your last idea. I'll submit that to the pyodbc project.  Thanks!!!
