### ISSUE TITLE
Handle wildcard imports when building package export lists 

### ISSUE THREAD

**Issue by ncoghlan** [PyCQA/pylint#1394]
https://github.com/PyCQA/pylint/issues/535 was a request to support the `behave` BDD testing library, which uses the pattern of a wildcard import + expicit `__all__` in its package level code:

```
from behave.step_registry import *
from behave.matchers import use_step_matcher, step_matcher, register_type

__all__ = [
    "given", "when", "then", "step", "use_step_matcher", "register_type",
    "Given", "When", "Then", "Step",
    # -- DEPRECATING:
    "step_matcher"
]
```

This currently leads to errors for code like `from behave import given, when, then`:

```
E:  1, 0: No name 'given' in module 'behave' (no-name-in-module)
E:  1, 0: No name 'when' in module 'behave' (no-name-in-module)
E:  1, 0: No name 'then' in module 'behave' (no-name-in-module)
```

Based on the comments in https://github.com/PyCQA/pylint/issues/754, I'm assuming it isn't considered desirable to read even literal `__all__` assignments like the one involved here, but would it be reasonable to special case wildcard imports of submodules in packages and actually load the exported name list from the submodule?

**Comment by rogalski** [comment]
Hey @ncoghlan 

Import being wildcard is not an issue. The actual problem is [automagical population of `globals()`](https://github.com/behave/behave/blob/master/behave/step_registry.py#L102). I don't think we even aim for understanding such kind of constructs. Keep in mind that this code is not actually run in interpreter, so we would have to deduce that those objects would be there purely by examining AST.

If you want to support it, tip in astroid.brain is a way to go.

**Comment by ncoghlan** [comment]
Thanks for the clarification @rogalski - I'll take it up with the `behave` devs to see if the code can be restructured to be more linting friendly.

**Comment by essamzaroura** [comment]
How do you solve this problem, is there a Work around?

**Comment by ncoghlan** [comment]
Transferring the workaround from https://github.com/behave/behave/issues/641#issuecomment-495040105:

    from behave import given, when, then # pylint: disable=no-name-in-module
