### ISSUE TITLE
Question about managing a shared python instance to avoid "import-error" problems

### ISSUE THREAD

**Issue by kfowlersandvine** [PyCQA/pylint#1434]
The scenario we are dealing with is we have a server that runs our code validation scripts, basically a wrapper that runs a combination of flake8, pylint and some others to make sure our python code is up to standards.  The problem we are facing is with pylint's "import-error" warnings.  There are a wide variety of projects that make use of the scripts and keeping the instance of python on this server up to date with all the external packages(things installed via pip) is troublesome.  We do not want to pollute this python instance with all the packages for every project that might ever need to run against this script.   

Our current solution to this problem is having each project use inline disables for these kinds of errors( # pylint: disable=import-error).  This is not ideal.  What would be a better solution for this problem aside form globally disabling this warning in our pylint config file?  Possibly something with python virtual environments?  We have yet to come up with a good, lightweight solution for this problem.

**Comment by rogalski** [comment]
That's precisely an use case for virtual environments. You create independent copy of interpreter, install your code and all it's requirements _in this env only_, install pylint/flake8/whatever you want (also _in this env only_) and run all checks you want to run _while using interpreter from venv_.

While technically you end up with having multiple copies of your analysis tools (once per each environment), I'd argue that this is actually a plus. In this way you can bump a tool version independently per each project and you don't care that update may be blocked by only one of all tested tools.

There are multiple sources around the web about using virtualenvs and dedicated tools that help with dealing with them (`tox` being one of more popular). I'm closing it since it's nowhere near being a Pylint issue.

**Comment by fermulator** [comment]
So is it the expectation then that the analysis virtual environment has the SUPERSET of all packages ever needed/used by all projects?  How could one deal with version conflicts though? (i.e. project A requires pkg_foo==1.0.0, but project B requires pkg_foo>=1.2.0)

**Comment by fermulator** [comment]
The only way I can think is having to spin up a virtual environment, on demand, for ANYONE who wants to run the analysis tools, (say from a pip requirements.txt) - but this takes time and is slow ... even if automated.

**Comment by rogalski** [comment]
@fermulator you don't install `pkg_foo` in base environment. You install `pkg_foo==1.0.0` in venv A and `pkg_foo==1.2.0` in vnev B.

Yes, creating venv takes a little bit of time. That's why tools like `tox` we're proposed, where they automate creation of virtual environments, testing process etc. One of `tox` features is not to recreate virtualenv when previously created one is "correct" in terms of all dependencies.

Still, it's not at all a Pylint-related discussion.
