### ISSUE TITLE
XlsxWriter "no value for argument" for decorated method

### ISSUE THREAD

**Issue by AHLinJie** [PyCQA/pylint#1468]
### Steps to reproduce
1. pip inastall 
XlsxWriter==0.9.3
xlwt==1.0.0
2. .env/local/lib/python2.7/site-packages/xlsxwriter/worksheet.py
```
    @convert_range_args
    def data_validation(self, first_row, first_col, last_row, last_col,
                        options):
```
3. 
```
        workbook = xlsxwriter.Workbook('filename')
        worksheet = workbook.add_worksheet()
        source = '=Sheet3!${col}$1:${col}${last}'.format(col=1, last=2)
        worksheet.data_validation('{col}4:{col}504'.format(col=col), {'validate': 'list',
                                                                          'source': source,
                                                                          'error_title': u'choose select in drawdown!'})
```
### Current behavior

No value for argument 'last_row' in method call
No value for argument 'last_col' in method call
No value for argument 'data' in method call
No value for argument 'last_col' in method call
No value for argument 'data' in method call
No value for argument 'last_col' in method call
No value for argument 'data' in method call
No value for argument 'last_row' in method call
No value for argument 'last_col' in method call
No value for argument 'options' in method call
No value for argument 'last_row' in method call
No value for argument 'last_col' in method call
No value for argument 'options' in method call

### pylint --version output
pylint 1.7.1, 
astroid 1.5.2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

**Comment by rogalski** [comment]
[Decorator actually modifies public API of function conditionally, based on values passed in runtime](https://github.com/jmcnamara/XlsxWriter/blob/83551e372fc4795c9a77884abf4c5c76a0320fdb/xlsxwriter/worksheet.py#L70).

I'm quite inclined to close it at "will not fix" - since it's conditional, it's not solvable by astroid.brain tip. Unless `*.pyi` can be created for this case and we'll learn how to use them during inference process, chances that we'll be able to handle that correctly during _static_ check are very low.
