### ISSUE TITLE
Import error when a module is named the same as the parent folder, which is also a module

### ISSUE THREAD

**Issue by jrial** [PyCQA/pylint#1474]
### Steps to reproduce
1. Create a folder structure where the top-level path has the same name as a direct descendant, with a `__init__.py` in both the parent and sub folder.
2. Place code in subfolder
3. Create code that imports from the "subfolder" module.
4. set PYTHONPATH to parent folder.
5. Run the code.

A repo that showcases this issue has been prepared at https://github.com/jrial/pylint-import-issue-demo - when using this approach, the steps become:
1. git clone https://github.com/jrial/pylint-import-issue-demo
2. cd pylint-import-issue-demo
3. ./run_test.py
4. Follow instructions.

### Current behavior
Python thinks this is perfectly fine. Pylint doesn't, because it considers the top folder to be the location of the module to be imported.

### Expected behavior
Pylint does not consider the parent folder when attempting to load the module, to be consistent with Python.

### pylint --version output
No config file found, using default configuration
pylint 1.7.1, 
astroid 1.5.2
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

**Comment by PCManticore** [comment]
@jrial Sorry for the long wait! I tried testing this locally but couldn't actually reproduce your problem. The only time it went wrong is when I was running pylint with Python 3+ against your code, getting the same error as you, which was caused by having a print statement in `myproject.classes`. Other than that, this worked correctly for both Python 2 and 3 using the latest version.
