### ISSUE TITLE
pylint and __implements__ vs abc.ABCMeta

### ISSUE THREAD

**Issue by dstromberg** [PyCQA/pylint#1639]
Should I use __implements__ or abc.ABCMeta in my own code?

abc.ABCMeta seems to work better with pylint (?), but even it appears to have trouble detecting missing methods.

### Steps to reproduce
I've put some sample code at http://stromberg.dnsalias.org/svn/pylint-interface-experiment/trunk/  At that URL, pie is an __implements__ experiment, and pabce is an ABC experiment.

And twomod shows the problem with importing 2.x or 3.x code and abc.ABCMeta.   Pylint thinks things are fine, but they aren't - a method is missing.

### Current behavior
It _seems_ like pylint is ignoring __implements__, while abc.ABCMeta appears to be closer to working the way I'd expect it would.  However, pylint seems to be using __implements__ internally, so perhaps I'm missing something.

### pylint --version output
$ /usr/local/cpython-3.6/bin/pylint --version
below cmd output started 2017 Thu Aug 24 02:29:57 PM PDT
No config file found, using default configuration
pylint 1.7.1,
astroid 1.5.2
Python 3.6.0 (default, Apr 17 2017, 06:46:09)
[GCC 5.4.0 20160609]

Thanks!

**Comment by PCManticore** [comment]
If pylint has a false positive/negative, please report a new issue.
pylint doesn't care about ``__implements__`` for some time now, while it does take ``abc`` in consideration, e.g. when looking for ``abstract-method`` or ``abstract-class-instantiated``. While it does use ``__implements__`` entirely, it's because that's how it was implemented years ago and nobody had time to move pylint's code to abstract base classes.
