### ISSUE TITLE
Pylint incorrectly assumes type() and isinstance() are equivalent in usage

### ISSUE THREAD

**Issue by colinmcintosh** [PyCQA/pylint#1659]
### Steps to reproduce
```
class Vehicle(object):
    pass

class Truck(Vehicle):
    pass

# causes C0123 Using type() instead of isinstance() for a typecheck
print type(Truck()) == Vehicle        # prints False
```

In this case Pylint seems to suggest the use of `isinstance(Truck(), Vehicle)` which would return `True` and is not what is needed on that line. In this case we are trying to check that the object is an instance of Vehicle and is not an instance of a Vehicle subclass.

### Current behavior
A warning is displayed.

### Expected behavior
No warning should be displayed.

### pylint --version output
```
pylint 1.7.2,
astroid 1.5.3
Python 3.6.0 (default, Dec 30 2016, 14:56:01)
[GCC 4.8.4]
```

**Comment by rogalski** [comment]
I disagree, `type(Truck()) == Vehicle` returning `False` will be a violation for any object-oriented code that uses inheritance.

It's even stated in language docs:

> With one argument, return the type of an object. The return value is a type object. The isinstance() built-in function is recommended for testing the type of an object.

**Comment by colinmcintosh** [comment]
The the language docs state

> The isinstance() built-in function is recommended for testing the type of an object, __because it takes subclasses into account__. [emphasis mine]

Which I think makes it clear that you should not use isinstance() if you don't want to take subclasses into account. I don't believe that statement is intended to entirely prohibit the use of type() for type checking.

**Comment by rogalski** [comment]
We never prohibit user from doing anything. You are free to disable this warning if it does not suit your requirements.

I think we have a consensus where we sometimes suggest non-equivalent code, and pylint often does that and warns about _technically not errors, but common pitfalls_. Mutable default arguments to functions are not _errors_ by itself. There are usage models where exploiting their mutating behaviour is intended. Yes we still warn about it, just because almost all usages you encounter and mistakes. Same goes to e.g. `overlapping-exceptions` checkers.

**Comment by colinmcintosh** [comment]
Thanks for the response. That helps clear this up for me.
