### ISSUE TITLE
Automate the release process as much as possible

### ISSUE THREAD

**Issue by felixonmars** [PyCQA/pylint#1786]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by PCManticore** [comment]
Thanks. I pushed the new tag. We'll add support for `punch` or `bumpversion` in our release instructions so that we'll keep this in sync in the future

**Comment by PCManticore** [comment]
just had another issue where this would have been helpful. For astroid 2.0.2 the environment markers for `typed_ast` were somehow dropped, which meant that for Python 3.7 and for PyPy we were trying to install `typed_ast` even though we explicitly prohibit that via the environment markers. Not sure how I managed to push a package without them, but having a single place where the packages gets released would be tremendously useful

**Comment by PCManticore** [comment]
Just messed up the release of astroid 2.2.1 with incorrect environment markers for `typed-ast`, because my `setuptools` version was old enough to not support the syntax used [here](https://github.com/PyCQA/astroid/blob/master/astroid/__pkginfo__.py#L33). At this point we ought to move to an automatic release process with Travis and git tags instead of doing it from my machine.

**Comment by PCManticore** [comment]
OK the master for both `astroid` and `pylint` *should* have support for automatic deploys with Travis on new tags. This should improve the deploy process significantly given that it won't run on my machine any longer.
