### ISSUE TITLE
Quiet mode can't be specified - but sometimes needs to be

### ISSUE THREAD

**Issue by kbattocchi** [PyCQA/pylint#1863]
### Steps to reproduce
If you pass a configuration file at the command line using --rcfile, then the configuration file is output to stderr (since 1.8.0 - see #1519 and #1522).  If pylint is incorporated as part of a build system, this can be problematic since it now results in what looks like an error.  

The merged commit mentions logging in "non-quiet mode", but I can't find a way to enter "quiet mode" from the command line...  (but please let me know if I'm missing something obvious).

I don't understand the rationale behind using stderr rather than stdout to begin with; however if stderr must be used, please allow some way to actually enter "quiet mode".

### Current behavior
One diagnostic line is output to stderr, no matter what.

### Expected behavior
Nothing is output to stderr (at least if "quiet mode" is enabled).

### pylint --version output
pylint 1.8.2,
astroid 1.6.1

**Comment by brycepg** [comment]
It looks like pylint doesn't expose the quiet mode to the command-line for some reason. I've verified that the the quiet mode does work internally by setting quiet=1 in the super call here: https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L460
All that needs to be done is update the cli interface.

This issue is related to issue #1853
