### ISSUE TITLE
Check if `IniFileParser.write()` is writing out the option descriptions as comments in the file

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#1890]
If not, this needs to be added back in.

**Comment by fffergal** [comment]
Looks like stdlib configparser is being used, and configparser has no concept of internally representing comments, just stripping them when reading.

This could be an interesting one.

**Comment by fffergal** [comment]
Would adding the comments by reading the file back in and using regex to find the options and add the descriptions before them be controversial?

It sounds easier to maintain than extending configparser to handle comments.

**Comment by fffergal** [comment]
So looked back through the history. This used to be done by the deleted `OptionManagerMixin.generate_config`. It implemeted writing out INI files, and included help as comments. A lot of the ini formatting is still in utils. The current code in per_dir_config just uses the stdlib/backported `configparser` modue, which has a write method.

Could bring back some of the `generate_config` code, but I decided to see how it looks using the configparser output and going back to add comments. If it feels too wrong, relying on patterns instead of generating, can try again.

**Comment by fffergal** [comment]
Please see #1959. Some things in there that could well need further discussion.

**Comment by fffergal** [comment]
Some new changes ready on that PR. Would remove the reviewed-waiting-updates label but can't.

**Comment by AWhetter** [comment]
Closed via #1959
