### ISSUE TITLE
VSCode - E1101:Instance of 'Resource' has no 'spreadsheets' member

### ISSUE THREAD

**Issue by swolfe2** [PyCQA/pylint#1917]
### Steps to reproduce
1. Open VSCode, create new Python file
2. Copy all the code from [step 3](https://developers.google.com/sheets/api/quickstart/python) of the Google Sheets / Python Quickstart
3.  Paste into VSCode

### Current behavior
Error message appears: E1101:Instance of 'Resource' has no 'spreadsheets' member
![2018-03-05 17_00_50-quickstart py - python files - visual studio code administrator](https://user-images.githubusercontent.com/36700028/37002216-eb82452e-2096-11e8-9b9a-a6594ed43982.png)

### Expected behavior
There would not be an error, since code works fine.

### pylint --version output
1.8.2

**Comment by tobiasfielitz** [comment]
Same for `callLater` in twistd's `reactor`.

Steps to reproduce:

```
python3 -m venv env;
source env/bin/activate;
python --version;  # Python 3.6.3
pip3 --version;  # pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
pip3 install pylint twisted;
echo "from twisted.internet import reactor" > test.py;
echo "reactor.callLater(1, id)" >> test.py;
pylint test.py;
pylint --version;
python -c "from twisted.internet import reactor; print(dir(reactor))";
```

**Comment by Phi-Li** [comment]
Instance of `SQLAlchemy` (imported from `flask_sqlalchemy`) and `scoped_session` (defined in `sqlalchemy/orm/scoping.py`) will trigger the same error.

Checking code in [models.py](https://github.com/miguelgrinberg/flasky-first-edition/blob/master/app/models.py) will reproduce the problem.

Pylint version is 1.8.1.

**Comment by PCManticore** [comment]
There's no way for us to infer that `spreadsheets` method exists, because it is populated dynamically in the said `Resource` class. You can alleviate this through various means:
- use `generated-members` to populate the `Resource` class with any methods you need
- you can ignore the errors for this class using `ignored-classes`
- or you can just ignore the entire google API module with `ignored-modules` so pylint won't emit any `no-member` error coming from this library

Regarding the other comments, I'd suggest moving them to separate issues, as each one might have a completely different cause for why this error is emitted.

**Comment by tobiasfielitz** [comment]
Looks like twisted is dynamically generated too ..

**Comment by brycepg** [comment]
@PCManticore what do you think about ignoring no-member for classes which use dynamic generation of attributes? This would cut down on a lot of false-positives

**Comment by PCManticore** [comment]
@brycepg We already do that, in fact we have tons of checks that should prevent most of these false positives:

- We ignore the error if the object's class implements `__getattr__` or `__getattribute__`. We also have a bunch of other filters as well, which can be found here
https://github.com/PyCQA/pylint/blob/9dd34aaca46287d7eb680e3c87e14f7b737206b1/pylint/checkers/typecheck.py#L306

- We ignore the error whenever we have an uninferable path somewhere in the inference paths
  https://github.com/PyCQA/pylint/blob/9dd34aaca46287d7eb680e3c87e14f7b737206b1/pylint/checkers/typecheck.py#714 

- We even try to detect if it's a C library, so that the users could disable that particular error or enable `extension-pkg-whitelist` if they want to

In case pylint still fails, one could already use the solutions I mentioned in my earlier comment, such as `generated-members` or `ignored-classes/modules`. 
The problem here is not that pylint is dumb and can't detect that the attribute is dynamically generated, but that the way this library is implemented prohibits any static analysis over it: https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery.py#L1023

There is not a lot pylint can do to sanely analyse every library out there. That's why we offer alternative solutions, even though they are not perfect all the time.
In this particular case we could probably try to see if the class modifies `__dict__`, but we'd have to walk to tree to find that operation, and at this point I feel that most of pylint's checks have to use hacks in order to understand even the craziest code out there. This is unreasonable for a static analysis tool.

**Comment by brycepg** [comment]
@PCManticore While I agree that classes like this prohibit much static analysis, and that users shouldn't expect much, I think it wouldn't be a bad idea to walk the class functions to see if they've modified `__dict__` to avoid false positives. I think that particular check would be a part of getting sane (#746)
