### ISSUE TITLE
"turtle" module is not supported...

### ISSUE THREAD

**Issue by pangyiren** [PyCQA/pylint#1928]
### Steps to reproduce
1. open a file 
2. import turtle moudle
3. write something like this
<img width="679" alt="2018-03-13 11 08 15" src="https://user-images.githubusercontent.com/7457280/37323352-23d76f62-26be-11e8-9ad3-ea4f79b19720.png">

### Current behavior
When I use "turtle" module the code can't be correctly checked.
Although my code is right "pylint" still said something was wrong.

<img width="762" alt="2018-03-13 12 52 10" src="https://user-images.githubusercontent.com/7457280/37323237-645c579c-26bd-11e8-9aaf-780588233f60.png">

### pylint --version output
```
No config file found, using default configuration
pylint 1.8.2,
astroid 1.6.1
Python 3.6.4 (default, Mar  1 2018, 18:36:50)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by brycepg** [comment]
Looks like `turtle` uses [exec](https://github.com/python/cpython/blob/3.6/Lib/turtle.py#L3967) to define these functions, which pylint can't infer (being a static code analyzer). If anyone wants to contribute an [astroid(https://github.com/PyCQA/astroid/tree/master/astroid/brain) brain] for `turtle`, that would help.

Otherwise you can add `turtle` to your `ignored-modules` in your `pylintrc`

**Comment by PCManticore** [comment]
A third alternative would be to use `generated-members` to add additional members that pylint can't know about.
