### ISSUE TITLE
Refactor of MessagesStore.check_message_id(msgid)

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#2071]
This is a dicussion concerning the refactor of a function for in order to make #2036 easier to understand and implement.

So, this function in utils.py is called check_message_id and take an argument called "msgid", but the argument can be a msgid (C0111) or a symbol ("missing-docstring") and it return a MessageDefinition or raise an UnknownMessageError if the msgid or symbol does not permit to return the MessageDefinition properly.

Examples of utilisation : 

         try:
             return self.msgs_store.check_message_id(msgid).symbol
         except UnknownMessageError:
             # The linter checks for messages that are not registered
             # due to version mismatch, just treat them as message IDs
             return msgid

        try:
            # msgid is a symbolic or numeric msgid.
            msg = self.msgs_store.get_message_id(msgid)
        except UnknownMessageError:
            if ignore_unknown:
                return
            raise

* It sound more like a getter so maybe it should be renamed "get_message_definition(msgid_or_symbol) ?
* In the calling code, if we fail to retrieve the symbol we return a msgid, are they interchangeable everywhere ? Or could we limit retrieval of message definition by symbol or msgid ?
* If we need to be able to get by both, maybe we can have an optional argument for msgid and an optional argument for symbol, and at least one of them should be set ? This would makes the call more explicit.

I would be able to do the change relatively quickly because I refactored a lot of MessagesStore and took a lot of remarks into account for #2036 already.

**Comment by PCManticore** [comment]
1. `get_message_definition` sounds great!
2. Yes, message ids and symbols are interchangeable everywhere. I think the function is fine as is from the point of view of getting the message definition for an message id or symbol. Otherwise we'll have to check before calling it that we want either the definition for a symbol or one for a message, I prefer that check to be in `get_message_definition` instead.
3. See my previous point. It's fine as it is.
