### ISSUE TITLE
Abnormal test running time for `consider-using-join` test file

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#2251]
### Steps to reproduce
1. run `pytest pylint -k consider_join`
2. Watch how the test runs for a couple of seconds

### Current behavior
The given test triggers abnormal performance behaviour for a particular check (doesn't seem to be `consider-using-join` as I disabled that one and it was still taking too many seconds to complete)

### Expected behavior
For the test to complete faster than that.

### pylint --version output
master

**Comment by sushobhit27** [comment]
yup it takes around 20 sec, way more than other test cases.
Is it because of redundant test cases, e.g below 3 test cases seems similar

https://github.com/PyCQA/pylint/blob/18023f050f9db7d63df38ab0d18072b60aabee24/pylint/test/functional/consider_join.py#L43

https://github.com/PyCQA/pylint/blob/18023f050f9db7d63df38ab0d18072b60aabee24/pylint/test/functional/consider_join.py#L47

https://github.com/PyCQA/pylint/blob/18023f050f9db7d63df38ab0d18072b60aabee24/pylint/test/functional/consider_join.py#L105

**Comment by brycepg** [comment]
reusing the name `result` is causing a `20000` possible inference values, similar to PyCQA/astroid#579. I've reduce test time from `16s` to `2.26s` by limiting possible results to `100`
