### ISSUE TITLE
Reconsider "misplaced type annotation"

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#2299]
With pylint/astroid 2.0, I got a bunch of "misplaced type annotation" errors which are actually just comments which are formatted in an unfortunate way:

```python
# The Mozilla Developer Network says:
# type: This attribute defines the styling language as a MIME type
# (charset should not be specified). This attribute is optional and
# default to text/css if it's missing.
# https://developer.mozilla.org/en/docs/Web/HTML/Element/style
```

```python
# At least in init(), we can get errors like this:
# type: ConnectionError
# database text: out of memory
# driver text: Error opening database
# error code: -1
```

I'm not sure if the error is really necessary (I assume mypy would just ignore those?), and e.g. indenting the "quoted" text (i.e. `#     type: ConnectionError`) or adding extra chars in front of it (`# > type: ConnectionError`) still makes it fail.

It also causes pylint to not load the module at all it seems, as other modules now fail with:

```
qutebrowser/browser/history.py:31:0: E0611: No name 'sql' in module 'qutebrowser.misc' (no-name-in-module)
qutebrowser/browser/qtnetworkdownloads.py:421:8: E0611: No name 'mhtml' in module 'qutebrowser.browser.webkit' (no-name-in-module)
```

(which is especially confusing when you see those errors before `mhtml.py` or `sql.py` are processed)

**Comment by PCManticore** [comment]
Hi Florian,

I think this is caused by the use of `typed_ast` which is used for retrieving the type annotations via comments from the code. In this case it seems it incorrectly parses `type: This attribute ...` as a type comment and thus it expects a previous value to be defined on the same line, e.g. `a = 1 # type: ...`
You also get the same errors with `mypy` as well, as in:
```
a.py:2: error: misplaced type annotation
```

I think it's best if a ticket would be created against `typed_ast` to not fail on such patterns, or if it is possible, to update your comment to not be confused with a type comment.

**Comment by PCManticore** [comment]
Just to mention that this error is completely raised by `typed_ast` which we now use to parse Python files.

**Comment by The-Compiler** [comment]
Ah, thanks, I didn't consider that! I moved it to https://github.com/python/typed_ast/issues/62.
