### ISSUE TITLE
import-error swallows AstroidBuildingError instead of AstroidImportError and friends

### ISSUE THREAD

**Issue by mattsb42-aws** [PyCQA/pylint#2313]
### Steps to reproduce
1. Create files:

`repro.sh`
```bash
#!/bin/bash
virtualenv pylint19 -p python3.6
virtualenv pylint20 -p python3.6
virtualenv pylintpreview -p python3.6

source pylint19/bin/activate
pip install aws-encryption-sdk
pip install "pylint == 1.9.2"
deactivate

source pylint20/bin/activate
pip install aws-encryption-sdk
pip install "pylint == 2.0.0"
deactivate

source pylintpreview/bin/activate
pip install aws-encryption-sdk
pip install pylint astroid --pre -U
deactivate

echo "Testing with pylint 1.9.2"
source pylint19/bin/activate
pylint --version
pylint checkthis.py
deactivate

echo "Testing with pylint 2.0.0"
source pylint20/bin/activate
pylint --version
pylint checkthis.py
deactivate

echo "Testing with pylint preview release"
source pylintpreview/bin/activate
pylint --version
pylint checkthis.py
deactivate

```

`checkthis.py`
```python
"""Clear C0111"""

from aws_encryption_sdk.identifiers import Algorithm

Algorithm  # clear W0611 with pointless statement  pylint: disable=pointless-statement

```

2. Run `repro.sh`
```
$ ./repro.sh 
[...installing snipped...]

Testing with pylint 1.9.2
No config file found, using default configuration
pylint 1.9.2, 
astroid 1.6.5
Python 3.6.2 (default, Sep 27 2017, 23:10:31) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
No config file found, using default configuration

----------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: -45.00/10, +55.00)

Testing with pylint 2.0.0
pylint 2.0.0
astroid 2.0.0.dev4
Python 3.6.2 (default, Sep 27 2017, 23:10:31) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
************* Module checkthis
checkthis.py:3:0: E0611: No name 'identifiers' in module 'aws_encryption_sdk' (no-name-in-module)
checkthis.py:3:0: E0401: Unable to import 'aws_encryption_sdk.identifiers' (import-error)

----------------------------------------------------------------------
Your code has been rated at -40.00/10 (previous run: 10.00/10, -50.00)

Testing with pylint preview release
pylint 2.0.0
astroid 2.0.0.dev4
Python 3.6.2 (default, Sep 27 2017, 23:10:31) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
************* Module checkthis
checkthis.py:3:0: E0611: No name 'identifiers' in module 'aws_encryption_sdk' (no-name-in-module)
checkthis.py:3:0: E0401: Unable to import 'aws_encryption_sdk.identifiers' (import-error)

----------------------------------------------------------------------
Your code has been rated at -40.00/10 (previous run: -40.00/10, +0.00)
```

### Current behavior

Starting in `2.0.0`, Pylint can no longer find modules in one of our libraries.  It does not include any C modules, but I tried the `unsafe-load-any-extention` and `extension-pkg-whitelist` options that commonly come up in searches for this behavior, with no effect.

### Expected behavior

Before `2.0.0` Pylint could find it.

### pylint --version output

See output in reproduction steps.

**Comment by PCManticore** [comment]
Hi, thanks for creating an issue!

This was a weird one to debug as from a quick look it seemed that `pylint` should have imported your package correctly, since it doesn't use any potential problematic features (namespace packages and friends).

For context, pylint 2.0 uses `typed_ast` for getting access to type comments. When trying to parse the `identifiers.py` file, `typed_ast` suddenly fails with `misplaced type annotation (<unknown>, line 105)`. Not sure why as that type comment seem alright to me, so it might be a `typed_ast` bug. This exception gets transformed to an `AstroidSyntaxError` exception, which is expected. Where things get funky is later on in `pylint` where we catch `AstroidBuildingException` when we cannot import a module (https://github.com/PyCQA/pylint/blob/3a8635a9ef85759f96bfefd8edcd70e223fd12bb/pylint/checkers/imports.py#L654). This means it silently catches `AstroidSyntaxError` as well, which is inheriting from `AstroidBuildingException`. This behaviour results in `pylint` swallowing the original cause of your problem, considering that `aws_encryption_sdk` cannot be imported and most likely does not exist, resulting in the behaviour you are noticing.

We should definitely catch just the relevant exceptions here rather than catching everything with `AstroidBuildingException`. Also it's probably worth asking the `typed_ast` folks why that type comment is not proper, and most likely if you remove it, `pylint` will be able to import your module again.

**Comment by mattsb42-aws** [comment]
Interesting. I'll follow up with `typed_ast` to see if they have any thoughts. I wonder if it might be getting confused because we haven't finished covering that module with type annotations.

**Comment by mattsb42-aws** [comment]
To close to loop on this, in case you're interested. `typed_ast` was absolutely correct. I had the type annotation comment below the docstring rather than above. Fixing that removed the pylint issues I was seeing manifest.

**Comment by PCManticore** [comment]
Thanks for confirming that @mattsb42-aws ! All we need to do now is to fix the broad except in pylint so this kind of issues will be easier to spot in the future.
