### ISSUE TITLE
Figure out a better way of registering options?

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#2355]
All of the config parsers (the CLIParser and the IniFileParser) need the option definitions and so does the Configuration. Registering a checker means registering options, which means the PluginRegistry needs a callback function to give these options to all of these objects.

**Comment by Pierre-Sassoulas** [comment]
I would not mind for the processing of option to be handled by `argparse` or even better `confuse` or `click` in a simple manner. Optparse is deprecated since python 3.2.  Even if Optparse was state of the art, the Mixin classes are really confusing for me.  I think it's something we need to keep in mind : it's probably easier to nuke the whole thing and start fresh with a newer library than doing it little refactor of Optparse by little refactor of Optparse.

The checker could also use composition instead of inheritance in order to get their options. It would break the coupling we have right now between option parsing and code analysis. Changing the way option work is made very difficult because of this coupling. Test are using the checker by giving option to Optparse, so the refactor of option registering is huge because of that if you change the option registering you need to change the checker tests too (!).

So I think it might be necessary to first make the BaseChecker an independent base class before actually doing anything to make options registering better.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I think we can close this? There is still https://github.com/PyCQA/pylint/issues/5829, but I think that deserves its own issue and doesn't necessarily fall under this one.
