### ISSUE TITLE
not recognizing members of module

### ISSUE THREAD

**Issue by hros** [PyCQA/pylint#2417]
I am using the Gurobi optimization package (import gurobipy)

pylint does not recognize any of the functions in the package. for example

> model = gurobipy.Model()

results in the pylint error:

> [pylint] E1101:Module 'gurobipy' has no 'Model' member

although the function exists (btw, vs code recognizes all the functions allowing for code completion)

**Comment by PCManticore** [comment]
Hi @hros 

Thanks for creating an issue. Unfortunately I cannot find how to actually install `gurobipy` so can't really tell what the root cause is. I imagine though it's a combination of either gurobipy relying on a C extension package or relying on dynamic features for the import system. I suggest running `pylint` with `--extension-pkg-whitelist=gurobipy` as in `pylint --extension-pkg-whitelist=gurobipy`. This should help in case `gurobipy` is a C extension package, which should help pylint figure out how to load this package.
