### ISSUE TITLE
catching-non-exception for type inheriting from Exception

### ISSUE THREAD

**Issue by lazka** [PyCQA/pylint#2504]
### Steps to reproduce
1. Install PyGObject: https://pygobject.readthedocs.io/en/latest/getting_started.html
2. Run pylint on the following code:
```python
from gi.repository import GLib
try:
    pass
except GLib.GError as error:
    pass
```

### Current behavior

`a.py:4:7: E0712: Catching an exception which doesn't inherit from Exception: GError (catching-non-exception)`

### Expected behavior

No warning, since

`(<class 'gi.repository.GLib.GError'>, <class 'RuntimeError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>)`

### pylint --version output

```
__main__.py 2.2.0-dev
astroid 2.0.4
Python 3.6.6+ (default, Sep  1 2018, 01:05:25) 
[GCC 8.2.0]
```
Upstream report: https://gitlab.gnome.org/GNOME/pygobject/issues/263

**Comment by PCManticore** [comment]
Thanks for reporting an issue. I currently cannot install `pygobject` as I lack `libcffi`, but just by looking at the [source code](https://github.com/GNOME/pygobject/blob/master/gi/repository/__init__.py) I'm not entirely sure how `pylint` is supposed to find the exception. Also this might be confused by our [astroid brain tip](https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_gi.py) for this library, but didn't confirm it due to not having the library locally.

**Comment by lazka** [comment]
> e. I currently cannot install `pygobject` as I lack `libcffi`

Fair enough (do you mean libffi? we don't use cffi). Thanks for trying.

> but just by looking at the [source code](https://github.com/GNOME/pygobject/blob/master/gi/repository/__init__.py) I'm not entirely sure how `pylint` is supposed to find the exception

I don't expect it to figure out the type but also to not show a warning when it can't.

> Also this might be confused by our [astroid brain tip](https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_gi.py) for this library, but didn't confirm it due to not having the library locally.

Thanks, I'll give that a try.
