### ISSUE TITLE
What areas of the docs could use some love?

### ISSUE THREAD

**Issue by pzelnip** [PyCQA/pylint#2544]
## Question

Since I'm participating in Hacktoberfest I'm looking for easy-ish PR's to open on public projects.  I've also been using Pylint for some time so would love to "give back" to the project.  Wondering if there are particular areas of the docs that could be improved or focussed on?  What would be the best thing to add to the docs?  Tutorials?  Technical reference stuff?  Integration/use of Pylint with other tools?

Would appreciate any guidance on what would be most desirable/useful to add/enhance in the existing docs.

**Comment by PCManticore** [comment]
Hey @pzelnip 

Thanks for doing this! I wasn't aware of Hacktoberfest, but seems like a great idea to me. 
Regarding particular areas of docs, I think there are quite a few of them:

- better technical reference around some of pylint's features would be helpful, especially those that lead to more issues being created. Some of the topics could be extensions and how `--extension-pkg-whitelist` helps in case of getting `no-member` for such modules, or how `--ignored-classes`, `--generated-members` and `--ignored-modules` can help whenever dynamic features of Python are involved. There are a bunch of similar flags that could help fine tuning the linter, but that are mostly unknown to the users, unless they go explicitly to look for them in the features section of the documentation.

- would love to have a better How to Contribute documentation. I think right now we're in a relatively okay spot, that is we have enough instructions on how to write a patch and verify that your patch is good to go, but we don't quite have what goes before that, in the writing of the patch itself. For example, we could clarify how to write a simple check for a given idiom, or how to extend an already existing astroid transform to support a particular feature. I think that this section could be written by someone other than me as I would be biased in a way or another due to already being familiar with the codebase.

- message control would need some more love as well, especially some verbose description on how it works: http://pylint.pycqa.org/en/latest/user_guide/message-control.html

Feel free to poke through the current documentation, if you notice something might be good for improvement, give it a go.

**Comment by pzelnip** [comment]
Awesome thanks!
