### ISSUE TITLE
Exceeded maximum recursion depth with some python3-qgis bindings

### ISSUE THREAD

**Issue by basilrabi** [PyCQA/pylint#2550]
OS: Fedora 29
I have `qgis3` installed in my machine and included in the package are python3-bindings which are saved in `/lib64/python3.7/site-packages/qgis`.
Running pylint with most of the python modules in qgis works without issues, however, pylint hangs with the file below and returns `RecursionError: maximum recursion depth exceeded` when interrupted. 

```python
"""
test.py:
"""
from qgis.core import QgsVectorLayer
from qgis.gui import QgsSearchQueryBuilder

def testFunction(layer: QgsVectorLayer) -> QgsSearchQueryBuilder:
    """
    Test function.
    """
    return QgsSearchQueryBuilder(layer)
```

### Steps to reproduce
1. install qgis3
2. create the file `test.py`
3. run `pylint-3 test.py`

### Current behavior
Hangs indefinitely and when interrupted, returns recursion error.

### Expected behavior
Pylint successfully runs.

### pylint --version output
```
pylint-3 2.1.1
astroid 2.0.4
Python 3.7.0 (default, Aug 30 2018, 14:32:33) 
[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

**Comment by PCManticore** [comment]
Thanks for reporting a bug!

**Comment by PCManticore** [comment]
Alright, tried to reproduce this but installing qgis on MacOS doesn't seem so straightforward. Please make sure to test with the latest version namely pylint 2.4.4. Alternatively if you can provide a Dockerfile so that I could reproduce this myself, I can take another look, but as it stands right now, it's impossible to reproduce without spending some time to get qgis installed in my environment.
