### ISSUE TITLE
html report type problems

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#263]
Originally reported by: **Anonymous**

----------------------------------------

Please consider the following extremely simple piece of code:

#!/usr/bin/python

a = 1+2
a+=2

if a< 5:
    print "zero"

print a

When analyzed with pylint -f html file.py it gives:
<td>Exactly one space required around assignment
a+=2
 ^^</td>

and

<td>Exactly one space required before comparison
if a&amp;lt; 5:
    ^</td>

The first one is rendered in web browser as: " 	Exactly one space required around assignment a+=2 ^^"
So ^^ points at ... nothing? Source code formatting is lost (due to html nature).

The second problem is rendered as "Exactly one space required before comparison if a&lt; 5: ^"
It shares problem with first issue, but there's something additional. "<" is converted into "&amp;lt;" and displayed incorrectly.
I haven't looked at 1.2 code, but in 1.0 the reason is that it is escaped twice - once by cgi.escape() and then by html_writer.py:
    def visit_text(self, layout):
        """add some text"""
        data = layout.data
        if layout.escaped:
            data = data.replace('&', '&amp;').replace('<', '&lt;')
        self.write(data)

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/263

**Comment by PCManticore** [comment]
Closing this, since we removed support for HTML reporting in Pylint 2.0. I think we now have a better reporting through the JSON reporter, which can be used as a basis for prettier HTMLs, made by external tools. Also, it was always a second class citizen, having a couple of bugs such as this one and others, and the UI was too bare to be worth keeping it.
