### ISSUE TITLE
pylint breaks when parsing editorconfig with multiple entries of the same name

### ISSUE THREAD

**Issue by davethegr8** [PyCQA/pylint#2661]
I ran into this issue: 

```
configparser.DuplicateOptionError: While reading from 'project/.editorconfig' [line  8]: option 'insert_final_newline' in section '*' already exists
```

where my editorconfig setup was

```
[*]
end_of_line = lf
insert_final_newline = false
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

### Steps to reproduce
1. Have an editorconfig with duplicate entries
2. run pylint

### Current behavior

pylint throws an exception

### Expected behavior

pylint continues processing

### pylint --version output

```
pylint 2.2.2
astroid 2.1.0
Python 3.6.7 (default, Dec 21 2018, 14:26:19) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

**Comment by PCManticore** [comment]
Hi @davethegr8 Thanks for reporting an issue! This seems to be caused though by `isort`, not `pylint` itself, since we don't care about `.editorconfig` at all. But `isort` does and when it detects that invalid file, it leads to a crash which affects `pylint` as well. I suggest opening an issue with `isort` directly.
