### ISSUE TITLE
Allow certain short argument/variable names that make perfect sense

### ISSUE THREAD

**Issue by matkoniecz** [PyCQA/pylint#2709]
### Is your feature request related to a problem? Please describe

pylint complains about variable/argument names like `x`, `y`.

### Describe the solution you'd like

Whitelist variable names that are typically OK despite being really short

### Additional context
See https://github.com/mkenyon/rubocop/blob/master/config/default.yml#L792 for how Rubocop (linter for Ruby) solves it for their UncommunicativeMethodParamName equivalent

See #2018 for a related problem where short names are misleadingly described as not being snake_case

**Comment by PCManticore** [comment]
Please check the [good-names](http://pylint.pycqa.org/en/latest/technical_reference/features.html?highlight=good-names#basic-checker-options) option, which does exactly this.

**Comment by gitaarik** [comment]
And what about function/method names? I don't see a `good-func-names` option

**Comment by PCManticore** [comment]
@gitaarik You are probably interested in configuring `function-rgx`: http://pylint.pycqa.org/en/stable/user_guide/options.html. There is no `good-func-names` because it does not make sense to have one. While `good-names` is a finite number of variables names, a function name cannot be easily determined to be good or not.

**Comment by gitaarik** [comment]
Sorry, the `good-names` option apparently does work for me! I was just editing the wrong file :joy:. Thanks anyway.
