### ISSUE TITLE
pylint doesn't seem to work with PETSc

### ISSUE THREAD

**Issue by MiguelArriaga** [PyCQA/pylint#2728]
## Question
I tried to create a simple script using petsc4py but it seems that pylint cannot see inside PETSc. Running the code below works fine:
```
import petsc4py, sys
petsc4py.init(sys.argv)
from petsc4py import PETSc
A = PETSc.Mat()
```
but if I run pylint on it (`pylint -E`) I get the following message:
`E1101: Module 'petsc4py.PETSc' has no 'Mat' member (no-member)`

Is there anything I can do to fix this?

**Comment by PCManticore** [comment]
@MiguelArriaga I have no idea what PETSc is. You might get this error because `PETSc` might be a C extension or might rely on an internal C extension, in which case you can try to run pylint with `--extension-pkg-whitelist=petsc4py.PETSc` and see if that fixes your issue. If not, you can try to fake that member with `--generated-members=Mat`. Or you can also disable the error for that module with `petsc4py.PETSC`.
Other than being a C extension, we might emit this error if `PETSc` uses dynamic features of the language, e.g. it patches the globals at runtime to add that `Mat` class, which is not an use case that a static analysis tool could solve easily.

**Comment by MiguelArriaga** [comment]
petsc4py is (afaik) a wrapper to C functions. However, adding "`--extension-pkg-whitelist=petsc4py.PETSc`" did not resolve the issue.
