### ISSUE TITLE
Segfault when importing module from PySide2

### ISSUE THREAD

**Issue by srottschaefer** [PyCQA/pylint#2796]
Hi,
I get a segmentation fault as soon as I import any module of PySide2.

### Steps to reproduce
1. New python file (test.py) with "import PySide2.QtWidgets" as content.
2. > pylint --extension-pkg-whitelist=PySide2 test.py

### Current behavior
Output:
************* Module test
test.py:1:0: C0304: Final newline missing (missing-final-newline)
test.py:1:0: C0111: Missing module docstring (missing-docstring)
Segmentation fault

### Expected behavior
Ideally, no segfault

### pylint --version output
pylint 2.3.1
astroid 2.2.4
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

Tested with PySide2 v5.12.1 on two different machines in otherwise clean virtualenvs.

**Comment by PCManticore** [comment]
Thanks, I can reproduce this issue. I don't know why it's happening though, there might be something that `--extension-pkg-whitelist` is doing something fishy.

**Comment by srottschaefer** [comment]
Ok, thanks. If you need help testing this at a later point I can probably shave off some time.
FYI: PyQt5 seems to work just fine.

**Comment by Thaodan** [comment]
[pylint.pyside2.log](https://github.com/PyCQA/pylint/files/2991417/pylint.pyside2.log)
I'm having the same issue on Arch Linux.
Attached coredumpctl info for help.

**Comment by AWhetter** [comment]
This was a PySide2 bug (https://bugreports.qt.io/browse/PYSIDE-942) that appeared only in v5.12.1 (as noted in https://bugreports.qt.io/browse/PYSIDE-937?focusedCommentId=447395&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-447395). v5.12.0, v5.12.2, and v5.12.3 are fine. It appears to be caused by accesses to `__doc__`. astroid touches every attribute and so it triggered this bug.
