### ISSUE TITLE
No-Name-In-Module can't recognize code with cython lib

### ISSUE THREAD

**Issue by cyw3** [PyCQA/pylint#2799]
### Steps to reproduce
1. a codebase with cython lib
2. pylint scan this codebase
3. report No-Name-In-Module issues

**Comment by PCManticore** [comment]
Hi @cyw3 Unfortunately without clear reproduction example, there's no way to figure out what the issue is all about. A potential solution would be to use `--extension-pkg-whitelist` to tell `pylint` to load those  Cython libs, in case they are compiled into C extensions, such as in `--extension-pkg-whitelist=the_name_of_the_module`.

**Comment by cyw3** [comment]
Does `--extension-pkg-whitelist=the_name_of_the_module` support fuzzy matching?

**Comment by PCManticore** [comment]
@cyw3 No, it does not.

**Comment by chbndrhnns** [comment]
I would have another reproducible [example](https://github.com/samuelcolvin/pydantic/issues/992#issuecomment-553529558) for that error message. Would you consider reopening this issue in case you can reproduce?
