### ISSUE TITLE
subprocess.run without check= argument

### ISSUE THREAD

**Issue by apnewberry** [PyCQA/pylint#2848]
### Is your feature request related to a problem? 

```python
import subprocess

subprocess.run(["cat", "-n"])
```

[`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run) uses a default of `check=False`, which means that a nonzero exit code will be ignored by default, instead of raising an exception. I'm always worried about forgetting to add `check=True`.

From the Zen of Python,

```
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
```

### Describe the solution you'd like 

`subprocess.run()` should always be invoked with an explicit `check=` argument, either `True` or `False`, to make clear what the error-handling behavior is.

**Comment by PCManticore** [comment]
@apnewberry This sounds like a great suggestion, thank you.

**Comment by sanyassh** [comment]
This feature conflicts with Pycharm check that says "argument equals to default parameter value". Also, it doesn't make much sense. Why did you choose only subprocess.run? Why not handle every default value for every function like def foo(handle_errors=False)? The answer for last question is "default values are made exactly for this: to omit passing them explicitly".

**Comment by gpshead** [comment]
I'm _considering_ disabling this checker by default for everyone at work as I've been unaware of anyone actually being tripped up by expecting an exception from `run()`.

As documented in its docstring help text and the subprocess module docs, `subprocess.run(()` returns a `CompletedProcess` instance which contains all relevant information including exit status (returncode).

Not _every_ process means "error" when it exits non-zero.

Then again, I'm the subprocess maintainer, so perspective from a lot of users would be more useful than my opinion.

**Comment by jtrakk** [comment]
> Why did you choose only subprocess.run? Why not handle every default value for every function like `def foo(handle_errors=False)`? 

There are not very many functions with a default behavior of hiding errors, because it has tendency to cause incorrect behavior. That's presumably why it's in the Zen of Python, and why [newer APIs](https://trio.readthedocs.io/en/stable/reference-io.html#trio.run_process) aren't designed that way.

**Comment by gpshead** [comment]
Please don't quote the zen. It isn't a rule book. It is written
intentionally vague and contradictory so that you can justify all possible
decisions using it.

**Comment by jtrakk** [comment]
> Then again, I'm the subprocess maintainer, so perspective from a lot of users would be more useful than my opinion.

It's great to see maintainers interested in users' opinions! Even when I'm ultimately wrong I certainly appreciate being listened to.

> It isn't a rule book.

You're right of course, the Zen isn't gospel -- it's simply a concise and lighthearted way of highlighting certain design considerations. 🙂

However — I do think those are the dominant considerations in this case. In particular, when I see `subprocess.run(args)` during code review, I want to know what happens if the process fails, because I have an internal mental linter that tells me "warning: that function silently hides errors". But if I'm tired I might not notice, and even if I do notice, I'd rather a robot have warned the developer about it in advance so it doesn't need to go through a human review cycle. 

As you rightly point out,

> Not every process means "error" when it exits non-zero.

Likewise, not all exceptions raised are actually errors (`StopIteration` comes to mind). On the other hand, _very many_ processes do mean mean error when they exit nonzero. So if a subprocess call does silently suppress errors, the code can be clarified by saying "I actually do intend to do this otherwise risky thing". My preference would've been that `subprocess.run(check=True)` be the default, but that's not an option (for backward compatibility reasons). But we can write our calls to be either safe (`check=True`) or signposted (`check=False`) -- which, while verbose and unorthodox (passing the default value), is nonetheless the best option under the circumstances.

**Comment by gpshead** [comment]
As a data point: In our internal codebase I see ~150 files passing an explicit `check=False` to `subprocess.run()` and <20 with a `# pylint: disable=subprocess-run-check` (out of thousands of subprocess.run calls, most written before pylint 2.4, roughly half of which seem to have `check=True`) so it seems to be having the intended effect.  People are being more explicit in their calls when using subprocess.run as a result.  Those who are annoyed are a minority and just disable it and move on.

**Comment by hippo91** [comment]
@gpshead and @jtrakk thanks for this interesting discussion.
@gpshead if i correctly understand your last post, the experience you had with your codebase indicates that this pylint check is useful. Is that correct?

**Comment by gpshead** [comment]
It _appears_ to be leaning towards useful.  I don't have a way to measure and judge if this has prevented actual bugs, all I can really measure are user complaints about particular lint warnings or how often they're disabled.

**Comment by hippo91** [comment]
OK thanks @gpshead .
