### ISSUE TITLE
Error installing pylint for python3.7 on cygwin

### ISSUE THREAD

**Issue by pjtallon** [PyCQA/pylint#2886]
## Issue
When trying to install pylint using pip, I get [these logs](https://github.com/PyCQA/pylint/files/3121983/pip3_install_pylint_logs.txt) that seem to be caused by a compilation issue due to a missing Python.h source file.

I checcked for its existence and found these matching files :
/cygdrive/c/Users/jtallon/AppData/Local/Programs/Python/Python37/include/Python.h
/cygdrive/c/Python27/include/Python.h

Which make sense in my current setup since I installed both python 2.7 and 3.7 on my cygwin terminal.

I'd like to be able to install pylint on my cygwin for my daily work, so it would be great to have a workaround for the least :)

## Leads explored :
I tried https://github.com/PyCQA/pylint/issues/2592 in case it could fix the issue
and also to install a specific pylint version for python3.7 which I have no been able to find using "pip search pylint".

Any help would be very much appreciated :)

Best,
Julien

**Comment by PCManticore** [comment]
Hey @pjtallon Thanks for opening an issue. The problem seems to stem from `typed-ast`. We are using it to have type information available to our inference engine. Unfortunately `typed-ast` is a C extension, which is why we install it only if the running interpreter is CPython based. But `typed-ast` also provides some wheels, which mean you should not need to have a C compiler to install it. Take a look at https://pypi.org/project/typed-ast/#files, it might be that your platform does not have a compatible wheel and thus you'll need a C compiler to get this installed. Sorry for all the hassle here, but I believe this issue would be better addressed on typed-ast's side, it would be great if you could create an issue on their side.
