### ISSUE TITLE
Pylint does not scan files in pytest folder

### ISSUE THREAD

**Issue by ndclt** [PyCQA/pylint#2919]
With a project using pytest, the files under the tests folder are not scanned when using pytest (thus without `__init__.py` files).

### Steps to reproduce
1. clone https://github.com/ndclt/bug_pylint
2. install package (pylint is a requirement) `pip install -e .`
3. run pylint on  `one_package`
4 run pylint on `tests` (no errors are printed).

### Current behavior
Only the error in the `one_file` is printed:
```
************* Module one_package.one_file
one_package/one_file.py:6:4: W0612: Unused variable 'not_used_variable' (unused-variable)
```

### Expected behavior
I also want to see the error in the file `one_package/tests/test_one.py`
```
************* Module test_one
one_package/tests/test_one.py:6:4: W0612: Unused variable 'not_used_variable' (unused-variable)
```

### pylint --version output
```
pylint 2.3.1
astroid 2.2.5
Python 3.7.2 (default, Mar  4 2019, 13:55:16) 
[GCC 5.4.0 20160609]
```

**Comment by PCManticore** [comment]
Alright, this happens because that `pylint one_package` means that `pylint` will consider the argument a module / package, rather than a list of directories. `pylint` will not go recursively to find all files in subdirectories in that case. Because `tests` is a directory with no `__init__` files, `pylint` does not include it in the list of files / directories to be analysed.

The solution here is to indicate to `pylint` that you want the directory to be analysed recursively, e.g. via something like `pylint one_package/*`.

**Comment by ndclt** [comment]
Thank you for your answer.

It perfectly works.

**Comment by bittner** [comment]
IIRC, this used to be considered a feature of pytest's suggested [Tests outside application code](https://docs.pytest.org/en/latest/goodpractices.html?highlight=__init__#tests-outside-application-code) setup. This way there would be no [tests](https://pypi.org/project/tests/) module that could unintendedly be imported (à la `import tests`). – Today, the pytest docs don't state this so clearly anymore.

Technically, this problem is related to #352.
