### ISSUE TITLE
Pylint ERROR Modeule not found if importing compiled python module/file

### ISSUE THREAD

**Issue by avivnaaman** [PyCQA/pylint#2949]
### Steps to reproduce
1.
2.
3.

### Current behavior
if I'm importing compiled file, it doesn't recognize it as importable module, throws error, although it works when launching.
of course, doesn't recognize methods and classes.
,
python 27

### Expected behavior
import like normal module.

### pylint --version output
pylint 1.9.4,
astroid 1.6.6
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]

**Comment by avivnaaman** [comment]
![Screenshot (135)](https://user-images.githubusercontent.com/34813756/59085807-76f4a900-8908-11e9-8dde-07b72eb352b1.png)
![Screenshot (134)](https://user-images.githubusercontent.com/34813756/59085808-778d3f80-8908-11e9-8aac-68367e9b0b45.png)

**Comment by PCManticore** [comment]
Hey @avivnaaman If it is a compiled module, in order for pylint to understand it, you need to pass `--extension-pkg-whitelist=module_name` to pylint, to let it know that it should import the module in Python before attempting any analysis on it. Otherwise there is no way for `pylint` to figure out how the code looks if it is compiled.
