### ISSUE TITLE
False positive warning from python 2 although python is 3+

### ISSUE THREAD

**Issue by ohlr** [PyCQA/pylint#2982]
### Steps to reproduce
https://github.com/microsoft/vscode-python/issues/5741#issuecomment-506014714

### Current behavior
`warning,no-absolute-import:import missing "from __future__ import absolute_import"
`
should only be issued for python2 but it is also issued whith for example python 3.7

### Expected behavior
These warnings should not be shown

### pylint --version output
Python 3.7.3
pylint 2.3.1

Error is likely to only occur on Linux OS

**Comment by PCManticore** [comment]
@ohlr From the linked issue it seems you are enabling the Python 3 porting checks, which this check is part of. These checks are emitted for both Python 2 and 3 as it is expected to lint a codebase that is Python 2 with the Python 3 version of the linter. The fix is to add a `python3` to the disable list, e.g. `--disable=python3`.
