### ISSUE TITLE
Can`t ignore path with ignore option or config file. Ignore option doesn`t work

### ISSUE THREAD

**Issue by makmary170** [PyCQA/pylint#2998]
### Steps to reproduce
For example - models.py doesn`t ignoring
```
/code # pylint ./core/models.py --ignore=./core/models.py
************* Module core.models
core/models.py:64:0: C0303: Trailing whitespace (trailing-whitespace)
core/models.py:65:0: C0303: Trailing whitespace (trailing-whitespace)
core/models.py:66:0: C0303: Trailing whitespace (trailing-whitespace)
core/models.py:67:0: C0303: Trailing whitespace (trailing-whitespace)

------------------------------------------------------------------
Your code has been rated at 8.86/10 (previous run: 8.86/10, +0.00)


/code # ls core/
__init__.py  __pycache__  admin.py     apps.py      migrations   models.py    tests.py     views.py
```

I add ```ignore=migrations``` in setup file too - nothing happened.

### pylint --version output
pylint 2.3.1

**Comment by makmary170** [comment]
@PCManticore

**Comment by PCManticore** [comment]
From the documentation (http://pylint.pycqa.org/en/latest/technical_reference/features.html#general-options):

```ignore: | Add files or directories to the blacklist. They should be base names, not paths.```

Right now `ignore` does not support paths. This is something we will fix at some point in https://github.com/PyCQA/pylint/issues/2279.

I'm closing this one as a duplicate since it pertains to the same topic.
