### ISSUE TITLE
pylint "module has no member" error when using with embeddable python 

### ISSUE THREAD

**Issue by sole6** [PyCQA/pylint#3082]
## Question
I installed pylint 2.3.0 (using pip) in embeddable python 3.6.
However, i get  a lot of E1101: "module has no member issue." 
For e.g.  Module 'socket' has no 'SOL_UDP' member.
But i don't get the same error when trying it out from cmd. (import socket, socket.SQL_UDP.

Can someone please help me explain this? 
I noticed if i move all the .pyd files to a DLLs folder (for e.g. _socket.pyd), the issue seems to disappear.

**Comment by PCManticore** [comment]
Hey @sole6 Thanks for creating an issue. I'm not entirely familiar with embeddable Python, can you post a link here for context? 

Regarding the issue you are seeing, `pylint` needs access to the source code of the libraries in order to create representations of the code internally. For builtin modules though, such as `socket` and friends, it needs access to the module in question in order to *import* it and build the same representations from the live module. This happens only for builtin modules such as `socket` though, so there should be no security concern regarding this mechanism.

In this case it is entirely possible that `pylint` needs access to the DLLs folder to be able to construct this representation.

**Comment by sole6** [comment]
Here is the download link for embeddable python 3.6 
https://www.python.org/ftp/python/3.6.0/python-3.6.0-embed-amd64.zip
Other details 
https://docs.python.org/3/using/windows.html

**Comment by PCManticore** [comment]
Taking a look at the embeddable Python and this seems like something we cannot support out of the box. Sorry that I have no better news for you.
