### ISSUE TITLE
Running PyLint recursively on my folders of python files

### ISSUE THREAD

**Issue by GeoffreyPlitt** [PyCQA/pylint#3084]
## Question

I can't seem to find this: I'd like to run pylint recursively on my directory structure, on folders of folders of python files (python files may be in any folder in the hierarchy).

I'd like the exit code of pylint to be 0 if all had no errors, non-zero if any had errors. This way, in my continuous build, I can just run tests if lint passed, or stop if it failed.

**Comment by PCManticore** [comment]
Hey @GeoffreyPlitt `pylint` currently does not support recursive analysis on directory structures (apart of those directory structures being packages or namespace packages). You'd have to list all Python files or Python root directories and pass those to `pylint` as arguments.

**Comment by bittner** [comment]
This is a common pitfall of developers new to Pylint. Because other tools, such as `flake8`, default to, "check my entire project". For a reason, for simlicity. I'm watching this problem pattern for years.

There might be a technical reason why we need to specify *modules_or_packages*, as the help screen says, which actually includes the possibility to specify file names. – Wait! Why file names but not directories? That's where the discussion starts.

In theory, it should be trivial to traverse a directory tree and process every single file; or discover the modules or packages, and then start processing. There should be no need to explicitly specify which module(s) or package(s) to process, unless I want to specificly do this.

Can we reopen the issue and discuss this matter?

**Comment by bittner** [comment]
Issue #2919 belongs to the same problem domain.

Also, I found out there is a much older issue, #352, that discusses solving this topic. :+1:
