### ISSUE TITLE
Check attrs attr.ib default= for dangerous defaults

### ISSUE THREAD

**Issue by scop** [PyCQA/pylint#3184]
It would be nice to have attrs `attr.ib(default=...)` values run through the dangerous-default-value check: http://www.attrs.org/en/stable/api.html#attr.ib

There's already some attrs specific functionality in pylint proper, so maybe this would be acceptable as well?

**Comment by PCManticore** [comment]
Yeah, I'm not sure about that. While we do have some `attrs` specific stuff, it's mostly related to properly infer them and `dataclasses` as well, while this one is a specific check for a third party library. I think this could be a separate third party package with specific `attrs` checks rather than living in `pylint` itself.
