### ISSUE TITLE
Setting to include Module 

### ISSUE THREAD

**Issue by SheepDomination** [PyCQA/pylint#3192]
What is the setting within a `pylintrc` file to include a module for linting  ? As I'm getting an error from Pylint that it cannot find the module for linting.

**Comment by PCManticore** [comment]
@SheepDomination That might happen because Pylint cannot find any source for the module in question. Is it a C extension? In that case you'd need to add it to `--extension-pkg-whitelist=` option. Is that module installed somewhere `pylint` can find? If not, then `pylint` will emit the `import-error` as it needs the source to build an AST from it. Other than that, please check the documentation on https://pylint.pycqa.org.
