### ISSUE TITLE
rcfile setting does not work?

### ISSUE THREAD

**Issue by PhilipBloom** [PyCQA/pylint#3329]
Sorry, unsure if this should be a support question but I also can't for the life of me find the docs for the rcfile setting in a pylintrc file (dug for a while https://docs.pylint.org/ and in google).

### Steps to reproduce
1. Create a pylintrc file with any settings
2. Create another one with rcfile=<otherone> that is in current directory with a python file that 
3. pylint python file,

### Current behavior

will only use settings from the first pylint file

### Expected behavior

Would override with the pylint file?  https://github.com/PyCQA/pylint/issues/618 seems to indicate it's been merged in but maybe I'm just confused.  What is rcfile for if not that?  Sorry for the mixture of bug/support question.

### pylint --version output
pylint 2.4.2
astroid 2.3.1
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by PCManticore** [comment]
So #618 has not landed yet, it's still work in progress and I'm afraid right now it's on hold, since it would require too many changes to get it done properly for shipping.

With that out of the way, right now `--rcfile` is supposed to be passed only at command line, if you want to control what configuration file you want to load. Due to a bug we're adding it in the configuration file but I'll push a commit shortly to stop doing that.

Hope that clarifies the situation.

**Comment by PhilipBloom** [comment]
Thanks, it being in the configfile but undocumented is what confused me.  Appreciate the response.
