### ISSUE TITLE
extension-pkg-whitelist=python_qt_binding not working 

### ISSUE THREAD

**Issue by bionade24** [PyCQA/pylint#3398]
[Python_qt_binding](https://github.com/ros-visualization/python_qt_binding) is a Qt binding helper. I even whitelisted PyQt5 and PySide2, but nothing helped.
### Steps to reproduce
1. Set python_qt_binding on whitelist
2. run pylint on file import Qt components via python_qt_binding
3. run `pylint --unsafe-load-any-extension=y`

### Current behavior
`Unable to import 'python_qt_binding.QtWidgets`

### Expected behavior
`Unable to import 'python_qt_binding.QtWidgets` should disappear after whitelisting

### pylint --version output
pylint 2.4.4
astroid 2.3.3
Python 3.8.1 (default, Jan  8 2020, 23:09:20) 
[GCC 9.2.0]

**Comment by PCManticore** [comment]
Thanks for the report. Unfortunately `unsafe-load-any-extension` would not help here since the root module (`python_qt_binding`) is not an extension. Also `QtWidgets` and similar modules are added at runtime via `sys.modules` patching which is not a behaviour that is supported by pylint at this moment:

https://github.com/ros-visualization/python_qt_binding/blob/melodic-devel/src/python_qt_binding/__init__.py
