### ISSUE TITLE
constant identification false positive

### ISSUE THREAD

**Issue by beauxq** [PyCQA/pylint#3466]
### Steps to reproduce
    """ constant test"""

    my_number = 1
    if my_number:
        my_number += 1

### Current behavior
    pylinttest.py:3:0: C0103: Constant name "my_number" doesn't conform to UPPER_CASE naming style (invalid-name)

### Expected behavior
no problem, `my_number` is not a constant

### pylint --version output
    pylint 2.4.4
    astroid 2.3.3
    Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
    [GCC 8.3.0]

**Comment by craynic** [comment]
A module variable should be a constant, no matter whether you use it as a constant.
You could use `--good-names=my_number` to mute this message.

**Comment by beauxq** [comment]
If that is the case,  then that is what the message from pylint could say.

Instead of pretending it's a constant when it's not, pylint could say that it should be a constant because it's a module variable.

**Comment by v7a** [comment]
I think pylint behaves correctly in your specific example here. Since `my_number` is only modified at module level, it still is a "constant" as in it will never change again.

And even if you modify it in a function using the `global` keyword, pylint discourages its use, and assumes you use only constants.

**Comment by PCManticore** [comment]
Hey, thanks for opening an issue.

Pylint's `invalid-name` check is rather dumb, and assumes that all module level variables are Constants.

The original rule was changed in 2.5.0 so the constant check will **only** apply to constant nodes, such as integers, numbers, strings etc (but things like mutable collections and such are exempted by default)

Regardless of which object is assumed to be a **constant** or not, `pylint` does not check that the object is mutated or not during the module scope, which is why you are seeing this error. This is definitely by design as @v7a already mentioned.
