### ISSUE TITLE
n=int(input('Enter how many tuples you want to add : ')) l=list() for i in range(n):     t=tuple(map(int,input().split()))     l.append(t) minn='a' for i in range(len(l)):     if(min=='a' and i<len(l)-1):         if(len(l[i])>=2 and len(l[i+1])>=2):             minn= i if l[i][1]<l[i+1][1] else i+1         elif(len([i])>=2):             minn=i     else:         if(i==len(l)-1 and minn=='a'):             if(len(l[i])>=2):                 minn=i             elif(len(l[i])>=2 and l[i][1]<l[minn][1]):  #issue exist in this line            minn=i if(minn=='a'):     print("No tuple exists of length 2 or more") else:     print(l[minn])

### ISSUE THREAD

**Issue by Day-dreamer0** [PyCQA/pylint#3470]
### Steps to reproduce
1.
2.
3.

### Current behavior
showing the error 
but if i change that line with  if(minn!='a' and  len(l[i])>=2 and l[i][1]<l[minn][1]) 
then it works otherwise the error remains can you tell me the issue

### Expected behavior
no error should occur and it should run

### pylint --version output
command is not working although pylint is installed in my windows 10

**Comment by PCManticore** [comment]
Hey @Day-dreamer0 I'm sorry but I don't understand what this issue is about. Please post the code for which you are having an error in the issue description itself, not in the issue title. Also what is the error you are receiving exactly? The output would also be useful. As it is right now, this issue is not actionable, so I'm going to close it, but feel free to provide those extra details in case there's a valid error you are receiving.
