### ISSUE TITLE
When to release version 2.5.0?

### ISSUE THREAD

**Issue by daoiqi** [PyCQA/pylint#3483]
## Question

When to release version 2.5.0?

2.4.3 release about : 2019/10

https://github.com/PyCQA/pylint/blame/master/ChangeLog

**Comment by thisch** [comment]
I asked this also in https://github.com/PyCQA/pylint/pull/3459

> Regarding the 2.5 release, we currently have one blocking issue #3361. Once that's fixed, we'll be able to release 2.5. This can also be seen in the corresponding milestone: https://github.com/PyCQA/pylint/milestone/22 While other milestones are not necessarily maintained, the 2.5 one is definitely up to date with our intentions

**Comment by PCManticore** [comment]
We have a PR ready that will close the 2.5 milestone: https://github.com/PyCQA/pylint/pull/3475 I'll pull it in this week and hopefully by the start of the next week 2.5 will hit PyPI. In the meantime please give it a go and let us know if you have any issues with 2.5 (e.g. crashes caused by the release will probably be fixed a lot faster than false positives)
