### ISSUE TITLE
Force source file encoding (via coding header or fully)

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#350]
Originally reported by: **Nikolai Prokoschenko (BitBucket: [rassie](http://bitbucket.org/rassie), GitHub: @rassie?)**

----------------------------------------

It would be nice to be able to enforce a consistent encoding on all project files. In particular, the presence of `coding` header should be checked as well as conformity to the header (i.e. decode the file with given encoding and see if it works).

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/350

**Comment by PCManticore** [comment]
Closing this.

This feature is more suitable to a custom Pylint plugin, rather than being implemented into the core itself. Regarding the last part, of decoding the file with the given encoding and see if it works, it works currently as well. If the file declares a given encoding, but it can't be decoded with it, we won't be able to parse and it will fail with a syntax-error anyway.

**Comment by moylop260** [comment]
For record, I have developed this feature from https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/checkers/format.py

 - A coding comment is required.
 - If you have a interpreter comment a chmod +× is required
 - if you have vim comments then emit a message
