### ISSUE TITLE
W0622 reported on import statement

### ISSUE THREAD

**Issue by andy-maier** [PyCQA/pylint#3677]
Pylint reports W0622 (redefined-builtin) on the import statement when a redefined builtin is imported into the namespace of the importing module.

Disabling this message on the definition of the redefined builtin still causes the message to be reported on the import statement.

A few versions ago, that did not happen (i.e. Disabling the message on the definition of the redefined builtin caused the message not to be reported on the import statement), but I did not check which version that was.

I do understand the idea behind reporting this, but it is very cumbersome for packages that define builtin symbols in their namespace (!) to deal with that.

### Steps to reproduce
1. `cat pylint_redefined_builtin/__init__.py`
```
"""
Test module for Pylint issue with redefined-builtin reported upon import
"""

from __future__ import absolute_import

from .conn import *  # line 7
```
2. `cat pylint_redefined_builtin/conn.py`
```
"""
Test module for pylint
"""

class ConnectionError(Exception):
    # pylint: disable=redefined-builtin
    "bla"

    def _dummy(self):
        return self
```
3. `pylint pylint_redefined_builtin/*.py`
```
************* Module pylint_redefined_builtin
pylint_redefined_builtin/__init__.py:7:0: W0622: Redefining built-in 'ConnectionError' (redefined-builtin)
```

The same behavior is exhibited when changing the wildcard import to import only `ConnectionError`.

### pylint --version output
pylint 2.5.3
astroid 2.4.2
Python 3.8.2 (default, Mar 11 2020, 00:28:52) 
[Clang 11.0.0 (clang-1100.0.33.17)]

**Comment by PCManticore** [comment]
Thanks for the report. Disabling on definition only works if you analyse the file where the definition is. But in this case, you would have to ignore it at the import level. 

The idea behind this check is to avoid shadowing builtins, which might result in subtle bugs if the defined object is used instead of the builtin one. It might be difficult for libraries, but as with all pylint checks, take it with a grain of salt and adjust it according to your needs.
