### ISSUE TITLE
Is there a way for pylint to bypass checking if Hz is a member of astropy.units?

### ISSUE THREAD

**Issue by texadactyl** [PyCQA/pylint#3750]
Source:
```
from astropy import units as apu
drift_rate = 2 * apu.Hz / apu.s
print(drift_rate)
```

Python3 execution (correct):
2.0 Hz / s

Pylint 2.5.3 execution:
2:17: E1101: Module 'astropy.units' has no 'Hz' member (no-member)

I realize that there is no way for pylint to know that astropy.units members will be known once the import statement is executed.  So, is there something that I can do, for example, in my $HOME/.config/pylintrc to tell pylint to bypass references to alleged members of astropy.units?

**Comment by plwalsh** [comment]
I *think* the problem here is that `astropy.units.Hz` is a [derived unit](https://github.com/astropy/astropy/blob/28d3cf17523af0cf9e5b2ab598109de3dd3a37c9/astropy/units/si.py#L106-L107) from `1 / astropy.units.s`, and ultimately added to the module differently. You can either add it specifically to the `generated-members` list, or add the entire module to the `ignored-modules` list.

From the command line:
```
$ pylint --generated-members=apu.Hz <file.py>
or
$ pylint --generated-members=apu.* <file.py>
or
$ pylint --ignored-modules=astropy.units <file.py>
```
Or in a `pylintrc`:
```
[TYPECHECK]
generated-members=apu.Hz
# or
ignored-modules=astropy.units
```

**Comment by texadactyl** [comment]
The pylintrc is always the best choice: one and done.  Also, there are other astropy.units member issues (same as Hz) so ignored-modules=astropy.units seems like the best solution.

Thank you.
