### ISSUE TITLE
Vulnerable Regular Expression in utils.py

### ISSUE THREAD

**Issue by yetingli** [PyCQA/pylint#3811]
**Type of Issue**
Potential Regex Denial of Service (ReDoS)

**Description**
The vulnerable regular expressions are located in

https://github.com/PyCQA/pylint/blob/2261844748be0f881719963d2fb5932dd4e4a2e2/pylint/pyreverse/utils.py#L54

https://github.com/PyCQA/pylint/blob/2261844748be0f881719963d2fb5932dd4e4a2e2/pylint/pyreverse/utils.py#L55

The ReDOS vulnerabilities of the regex are mainly due to the sub-pattern [^\W_]+\w* and can be exploited with the following string
"__"+"1"*5000 + "!"

I think you can limit the input length or modify these regexes.

**Comment by hippo91** [comment]
@yetingli thanks for the report.
It is very interesting. I am not at ease with security problems but very interested in. Can you develop a bit more what the problem is and how an attacker could exploit it. If it is not secure to develop more on this channel, feel free to send me a private mail.
As i understand, those regex could take a very long time to execute thus yielding to a DoS. Thats it?
