### ISSUE TITLE
Better "unnecessary elif after return" checking

### ISSUE THREAD

**Issue by TheTechRobo** [PyCQA/pylint#3815]
The problem: with [this code](https://gist.github.com/TheTechRobo/e703b164329de8ddded5cec9a111e26a), Pylint says "unnecessary elif after return" even though putting a `return` statement without the elif would prevent the rest of the code to run.

### Possible solution?
Checking if there is code after the elif in question.

### Additional context
Using CodeFactor with no `.pylintrc`.

**Comment by dbaty** [comment]
There may be a misunderstanding here. Pylint does not suggest to remove the whole `elif` statement. Pylint suggests to replace the `elif` statement by an `if` statement, like this:

```diff
if amount == 1:
    return [0,]
- elif amount == 2:
+ if amount == 2:
    return [0,1]
```

**Comment by hippo91** [comment]
@TheTechRobo thanks for the report.
@dbaty you are right! Thanks for clarifying this. Thus i'm closing this issue.

**Comment by TheTechRobo** [comment]
@dbaty Sorry for this interruption! Just wondering, why does it recommend that?

**Comment by hippo91** [comment]
@TheTechRobo pylint recommends that because there is no way the `else` part of `elif` statement can be reached.
If the code enters in `if` statement then it mandatory gets out by returning and there is no way it reaches the `elif` statement.
The only way the code goes on is to avoid entering the ìf` statement. Thus there is no need for an `else` or `elif` statement.
