### ISSUE TITLE
minor: isort 4.3.x does not work, 4.2.x and 5.x do

### ISSUE THREAD

**Issue by gpshead** [PyCQA/pylint#3881]
https://github.com/PyCQA/pylint/blob/master/pylint/__pkginfo__.py#L44 specifies `isort>= 4.2.5,<6`... but isort 4.3.21 doesn't appear to actually work.

why?  isort 4.3.x loses the` isort.SortImports.place_module()` API that is needed in https://github.com/PyCQA/pylint/blob/98d2c060ba0dbae6abecff2393cb6dd8a9bde97b/pylint/utils/utils.py#L435.

suggestion: either exclude 4.3 from your version constraint, or just bite the bullet and require >=5 anyways as that is probably what most people are using.

otherwise, figure out how to also make that utils.py IsortDriver compatibility layer also work with isort 4.3.x.  is that really worthwhile?

**Comment by dbaty** [comment]
I cannot reproduce the bug. I can successfully run pylint (the master branch) with isort 4.2.8, 4.3.0 and 4.3.21. (I would not use Git tags in GitHub isort repository as a reference. For example, the tag for 4.3.21 does not correspond to what is in the file on PyPI.)

That said, we could probably remove the support of isort 4 and require isort 5. When I worked on supporting isort 5 in pylint a few months ago, I kept pylint compatible with isort 4, because isort 5 dropped the compatibility with Python 3.5 and pylint still supported the latter. But Python 3.5 has [reached its end of life](https://www.python.org/downloads/release/python-3510/) at the end of September. Which means that we could drop the support of Python 3.5, and hence require isort 5.

If a maintainer confirmed that it's reasonable, I could work on this.

**Comment by gpshead** [comment]
oh, the github tag not matching the pypi release? ugh.  i rarely check for that.  okay, this can be closed.

agreed isort 4 support can be dropped.  but i don't think that needs an issue open to track it.  the next time anyone does something that needs more out of isort it should prove a natural simplifying cleanup to make.  i like that isort 5 gained an official api.

**Comment by hippo91** [comment]
@dbaty and @gpshead  thanks for your interaction! 
@dbaty for me it is ok to remove support for python 3.5 but i would like to know @AWhetter and @Pierre-Sassoulas opinions about this!

**Comment by Pierre-Sassoulas** [comment]
I also find reasonable to drop support for a version of python when it has reached end of life.
