### ISSUE TITLE
Use Squash Merge for merge requests

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#4084]
### Feature request
Only use **squash merge** from Github directly. 

### Current situation
As far as I can tell only a **normal** merge is used. The result is a long and complicated commit history. Take the last merged Pull Request as an example: https://github.com/PyCQA/pylint/pull/4074/commits. It includes many small commits, that also appear in the final history. Additionally there isn't even a merge commit and the pull request isn't linked. Just from the commit message it's nearly impossible to quickly find the pull request.

### Advantages
- The git history will only contain one commit per Pull Request
- The squash commit will automatically include the Github PR number and link to it
- Since every Pull Request will only be one commit, there should, in theory, be no commit that doesn't pass the tests. Currently, it's typical that one first implements a feature and later, in another commit, fixes the tests.
- `git blame` will be much more useful, especially on Github directly -> the PR is linked directly
- The individual commits are still preserved in the PR history and can be viewed that way
- The broader scope of a change will become more visbile
- It will be easier to fix errors caused by one merged Pull Request -> easier to identify and easier to cleanup; only one commit
- Easier to cherry-pick fixes to older branches

--

CC: @Pierre-Sassoulas

**Comment by Pierre-Sassoulas** [comment]
In my opinion, squashing a MR can make it impossible to understand. Look at [this one](https://github.com/PyCQA/pylint/pull/2809/files) for exemple. I also want the git history to be understandable without having to see github merge request for the detail. Usually I rebase + merge for clarity when the commit make sense and are atomic and squash only if the MR would require an interactive rebase that would not bring a lot of value. I expect that maintainers will make the right call for each situation and I don't think a rule is necessary .

**Comment by cdce8p** [comment]
> In my opinion, squashing a MR can make it impossible to understand. Look at [this one](https://github.com/PyCQA/pylint/pull/2809) for exemple. I also want the git history to be understandable without having to see github merge request for the detail.

I agree that with the squash commit itself, it would be pretty difficult to understand. I would however want to point out that this isn't a common use case (maybe I wrong here?). In my personal experience I almost only use `git blame` and only if I want to understand a specific code section. In that case it's really helpful to have a link to the Merge request to look at it in more detail, see related commits and most importantly read the description.

Additionally, with only squash commits, Github compare will be more readable and developer not familiar with the code can at least understand the squash merge messages in context. I've rarely seen good individual commit messages. One could even take the commit log as a big changelog.

Lastly, I believe it will make the planned new git flow easier to implement, using `git cherry-pick` just on one commit.

--
Im suggesting it, since I've seen with Home-Assistant how good it can work: https://github.com/home-assistant/core
In every release nodes they include a section **All changes** which just lists all commit messages.
https://www.home-assistant.io/blog/2021/02/03/release-20212/#all-changes

**Comment by Pierre-Sassoulas** [comment]
I agree that it's harder to see MR right now on github and I'd like to have a rebase then `merge --no-ff` option on github instead of just a rebase + merge fast forward. We could do an "all changes" by including all the merge request message in the same way without deleting the historic in git.

The thing is, I expect individual commits to be well thought by their author and they usually are reasonably well thought. I mean look at this MR by doublethefish: https://github.com/PyCQA/pylint/commit/854a7f55823206b8bd9d91095c3ca12d78d63f2a, https://github.com/PyCQA/pylint/commit/579b58d3583fb0efac58aaa8e4d63f6dcb05b0bb, https://github.com/PyCQA/pylint/commit/b41e8d940dbd0a92d2805a99eb0f97c01f620197, it would be a shame to squash it in a single commit.

Also, having a detailed historic makes a lot of thing easier in particular `git bisect` when blind debugging. If I want to see what introduced a bug, I'd rather have a small commit even with a non helpful message than a big squashed merge request with +500 -600 lines changes and a link to the merge request on github.

**Comment by Pierre-Sassoulas** [comment]
Closing because each maintainers  will choose what's best on a case by case basis.
