### ISSUE TITLE
Way to analyze docstring and comments

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#42]
Originally reported by: **BitBucket: [mitar](http://bitbucket.org/mitar), GitHub: @mitar?**

----------------------------------------

It would be great if there would be a way to access docstrings and comments in their native context. For example, here are some checks I would like to do:

 * check that docstrings start and end with """ (and not ''') on their own line
 * check that there is an empty line after closing """
 * check that TODO comments are of the form # TODO: Sentence.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/42

**Comment by PCManticore** [comment]
Closing this one. This can be done currently using the TokenChecker concept. It's a bit of work, yes, but it works. While do want to include the comments at some point into the AST, by bringing a new parser, they will be definitely cleaned up, since the plan is to use them for pragma disables, type comments or just general introspection of the code through the AST. Thus they won't contain the empty lines or spaces before them, this is far more suited to be in the current TokenChecker than in the AST (and they are there right now, by implementing the process_tokens).
