### ISSUE TITLE
Add --fail-on option to always return error code if specific issues (or issue types) are found

### ISSUE THREAD

**Issue by das-intensity** [PyCQA/pylint#4227]
We're using pylint in CI with two primary goals:

1. Ensure there are no error-category issues - this can be achieved by looking at the exit code
2. Ensure the overall linting score doesn't deteriorate too much - this can be achieved by using `--fail-under=8`

However if `--fail-under` is used, and the score is above that, then it passes even if there are error-category issues detected. Essentially it's acting as a "only throw fail (non-zero) codes if under this", instead of a "fail if under this, otherwise change nothing".

Two possible solutions I can think of here are:

1. Have a configuration option to prevent `--fail-under` from consuming other exit statuses. I.e. a way to say "if score is under N, return error code X, regardless of all else, otherwise change nothing".
2. Add a new option like `--fail-on=E,unused-import` which means that if there are any `E*` code (error-category) issues, or any `unused-error` issues, then fail, otherwise change nothing.

**Comment by hippo91** [comment]
@das-intensity thanks for this suggestion.

**Comment by das-intensity** [comment]
@hippo91 so I'm quite interested in getting this done (ideally the second option, `--fail-on`), and happy to do the dev myself. I just don't want to get a PR in for this, only to be **then** told it doesn't fit the design of pylint/etc. Do you have any suggestion on how to proceed? Just do it and pray, or are there people I should discuss the specifics with first?

**Comment by Pierre-Sassoulas** [comment]
I also like ``fail-on`` better, we already have a ``--error-only`` option so ``--fail-only-on`` would make more sense I think. @hippo91 and I are the most active admins right now, so consider this idea merge-able. Regarding what to do in the code the best thing to do would probably be to refactor the configuration handling to use arparse or click first (😄), because the configuration code in his current state might make it hard to make a simple reviewable patch. But feel free to read the code and come to your own conclusion.
