### ISSUE TITLE
Every option in setup.cfg is loaded, even when the section is unknown to pylint

### ISSUE THREAD

**Issue by SabaSCP** [PyCQA/pylint#4371]
This is a slightly different issue from what @mteiste has seen with #4272 . My issue is with all sections and options defined in `setup.cfg` are processed/loaded, even if those sections are for other tools and unknown to `pylint`.

This has the effect of setting pylint's ignore to `D107,D400,D401`.

Going through the code, it feels like the problem is somewhere in [option_manager_mixin.py](https://github.com/PyCQA/pylint/blob/c7ac7c0ec339e9a8d105ccac0e59e65cacb79272/pylint/config/option_manager_mixin.py), either at `read_config_line` line [298:299](https://github.com/PyCQA/pylint/blob/c7ac7c0ec339e9a8d105ccac0e59e65cacb79272/pylint/config/option_manager_mixin.py#L298:L299) or at `load_config_file` line [312](https://github.com/PyCQA/pylint/blob/c7ac7c0ec339e9a8d105ccac0e59e65cacb79272/pylint/config/option_manager_mixin.py#L312).

Apparently, Toml files are not affected because the logic is set to read from `content["tool"]["pylint"]`.  But for `setup.cfg` there's no `try / except` block, iterating through every section:

```
if sect.startswith("pylint."):
	sect = sect[len("pylint.") :]
if not sect.isupper() and values:
	parser._sections[sect.upper()] = values
```

I think `pylint` should filtered / excluded any section that's not part of any pylint group -> `self._mygroups`.

### Steps to reproduce

Given a config file `setup.cfg`

```
[pylint.master]
ignore = migrations

[flake8]
ignore = D107,D400,D401
```

### Current behavior

Result of `pylint --generate-rcfile | grep -A2 'ignore='`:

```
ignore=D107,
       D400,
       D401
```
-->

### Expected behavior

Result of `pylint --generate-rcfile | grep -A2 'ignore='`:

```
ignore=migrations
```

### pylint --version output

Result of `pylint --version` output:

```
pylint 2.7.4
astroid 2.5.3
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
```

### Workaround

I had to monkey patch https://github.com/PyCQA/pylint/blob/master/pylint/config/option_manager_mixin.py#L308 with
```
        if section not in self._mygroups:
            continue
```

Resulting in:

```
def load_config_file(self):
    """Dispatch values previously read from a configuration file to each
    options provider)"""
    parser = self.cfgfile_parser
    for section in parser.sections():
        if section not in self._mygroups:
            continue
        for option, value in parser.items(section):
            try:
                self.global_set_option(option, value)
            except (KeyError, optparse.OptionError):
                continue
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. Do you want to open a merge request with the proposed changes ? :)

**Comment by SabaSCP** [comment]
I wanted to get some insights / feedback first before jumping with the fix. I'm mostly concern on who's filling `self._mygroups` and if any external plugins are registered in here (`self._mygroups`).

**Comment by Marsfan** [comment]
I can confirm that this is indeed an issue. I have a single _setup.cfg_ file with both pylint and flake8 configuration options. I want to ignore a specific subdirectory with the `ignore=example` setting in `[pylint.MASTER]`

Elsewhere in my configuration file I have a `[flake8]` section with the option `ignore=E303` setting. Pylint reads this and sets its `ignore` setting to `E303` instead of `example`

It seems that pylint is not properly scanning only its own sections in the config file. 

Interestingly enough, re-ordering the sections makes no difference. if the `[flake8]` section is above `[pylint.MASTER]` the results is the same as when `[flake8]` is below '[pylint.MASTER]'

**Comment by Pierre-Sassoulas** [comment]
> any external plugins are registered to self._mygroups.

Good point, yes, I think so. The way it's done right now each plugin has his own section in the configuration so it can have arbitrary name added by external code. Theorically a ``flake8`` plugin could be added. We might have to make a breaking change to fix this, and it does not seem easy.

Thinking about two solutions on the top of my head:
- Adding pylint as a suffix to current configuration for unknown plugin group. Ie. : limited list of known plugin in order to not force ``MASTER`` to be changed to ``pylint.MASTER`` so we don't break all the conf file ever done for pylint, but ``pylint.external_plugin`` would be required instead of ``external_plugin``. And then we do not load everything obviously.
- Breaking change for 3.0 where we only use ``pyproject.toml`` and provide a converter for old configurations, then we do not bother fixing 3 conf formats in 4 possible files.
