### ISSUE TITLE
Reinstate `bad-whitespace` or at least make it optional.

### ISSUE THREAD

**Issue by 6shorts** [PyCQA/pylint#4389]
`bad_whitespace` was removed in v2.6.0 in favour of using black. We use PyLint as part of our assessment in an introductory course and don't want to require black on top of this. As a result we instruct downgrading to v2.5.3 and miss out on many new features being developed.

Could it be re-instated, perhaps as an optional feature which can be toggled in the rc file?

**Comment by Pierre-Sassoulas** [comment]
The problem with `bad-whitespace` is that the cost to maintain it is very high and there is'nt a lot of contributors to do it (because most of the one that could be interested never encounter the problem as auto-formatting fixes everything instantly). If you really want to fix your code manually, another tool that could warn you about formatting issue is `pycodestyle` (included in flake8).

**Comment by 6shorts** [comment]
PyLint is preferable as it is included in Anaconda, easily used in Spyder by novices and outputs a score we can translate to marks.

We included this aspect in our course to ensure consistency in marking style, but were pleasantly surprised when students started reflecting on their code further. Especially when encountering refactor warnings.

flake8 requires additional installation and is run through a terminal, both of these aspects are difficult when guiding novices when we want them to concentrate on learning how to code. Moreover asking our institution to install a new application across the department is nontrivial. Furthermore, no score is outputted making enforcing in assessments trickier. 

If we are in the minority wanting this change then so be it. We will have to stick with v2.5.3 and hope it remains compatible long-term.

**Comment by Pierre-Sassoulas** [comment]
So it seems you want to include the warning that can be fixed automatically by a tool in the actual mark of your students and make them fix it manually ? Just my opinion but as someone who really enjoy programming, it does not sound like a lot of fun (or the best use of dev time in the industry or otherwise). If I were you, I'd upgrade pylint, teach them about auto-formatter (maybe just a link to https://black.vercel.app/), and keep the aspect that make them really think about what matters in the code (refactoring, design, performance, and new ``2.7.0`` checks like ``consider-using-generator``) not about what can be automated by a tool.  Just my two cents.

Regarding the issue itself, multiple tools already exists to do that, most of them do not warn about the issue but fix them directly on saving the file. So the likeliness of a contributor willing to maintain it in pylint is low. But if someone (maybe you ?) is really motivated to maintain it during their free time... then we could add back an optional checker in pylint.
