### ISSUE TITLE
Permit to generate plantuml diagram with pyreverse

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4498]
### Describe the solution you'd like

Permit to generate plantuml code in output of pyreverse

### Additional context

https://github.com/PyCQA/pylint/issues/4488

**Comment by DudeNr33** [comment]
You can assign this issue to me - I have implemented a first basic draft. Implementing a PlantUml Writer and Printer class analogous to the DOT variants is straightforward.

However, there is one thing that I want to look into a bit further.
One big advantage of PlantUML is that even the text output is human readable. 
IMO an important use case for the PlantUML backend would be to generate a diagram from the existing code, and then use that to reason about changes to the software design, by modifying the diagrams and thus illustrating the proposed changes. 

Currently however the diagram generation relies on IDs to identify elements. 
The test data for ``pyreverse`` would look like this in PlantUML:
```plantuml
@startuml plantuml
class "Ancestor" as 0 {
    attr : str
    cls_member
    get_value()
    set_value(value)
}
class "DoNothing" as 1 {
}
class "Interface" as 2 {
    get_value()
    set_value(value)
}
class "Specialization" as 3 {
    TYPE : str
    relation
    top : str
}
3 --|> 0
0 ..|> 2
1 --* 0 : cls_member
1 --* 3 : relation
@enduml
```
While four classes are somewhat OK to remember by ID, this becomes unwieldy if the number of classes grows.

If someone wants to work with the file and modify it, it would be much more convenient if it could look like this:
```plantuml
@startuml plantuml
class Ancestor {
    attr : str
    cls_member
    get_value()
    set_value(value)
}
class DoNothing {
}
class Interface {
    get_value()
    set_value(value)
}
class Specialization {
    TYPE : str
    relation
    top : str
}
Specialization --|> Ancestor
Ancestor ..|> Interface
DoNothing --* Ancestor : cls_member
DoNothing --* Specialization : relation
@enduml
```

The need for IDs is of course due to the possibility that two classes in different modules can have the same name, which is not necessarily included in the diagram.
I have to dig a bit deeper into the code to see if there is a viable solution to solve this. Maybe only use the IDs if multiple classes (or modules, for package diagrams) with the same name exist.

**Comment by Pierre-Sassoulas** [comment]
Hey, thank you for tackling this, much appreciated ! The way I solved this issue when I was doing plantuml diagram was to use package. Would that be possible here ?
```plantuml
@startuml

package foo1 <<Node>> {
    class Ancestor {
        attr : str
        cls_member
        get_value()
        set_value(value)
    }
}

package foo2 <<Rectangle>> {
    class Ancestor {
        attr : str
        cls_member
        get_value()
        set_value(value)
    }
}

package foo3 <<Frame>> {
    class DoNothing {
    }
    class Interface {
        get_value()
        set_value(value)
    }
    class Specialization {
        TYPE : str
        relation
        top : str
    }
    DoNothing --* Specialization : relation
}

foo3.Specialization --|> foo1.Ancestor
foo1.Ancestor ..|> foo3.Interface
foo3.DoNothing --* foo1.Ancestor : cls_member

@enduml
```

**Comment by DudeNr33** [comment]
The way the ``DiagramWriter`` and ``DiadefsHandler`` classes are currently implemented not directly - they clearly distinguish between class objects and packages, as package and class diagrams are generated independently.
Thus, including a hierarchy of package->subpackage->class like in your example is not really possible.

Packages however can be automatically generated by using ``set namespaceSeparator .``.
This however mandates the use of the option ``--module_names``, which is ``False`` by default.
(When setting it to ``True``, the problem with name conflicts would be gone anyway, even without using packages).

One could use IDs if ``--module_names`` is set to ``False`` and proper names if it is ``True``. 
Or try to use proper names always and only fall back to IDs if multiple classes with the same name exist.
Or generate unique names by prepending module and optionally package name for conflicting classes, so the name is always as short as possible while still remaining unique (this would be pretty much like PyCharm does it in the files tab).

**Comment by DudeNr33** [comment]
Sometimes the solution can be so simple - just use the full qualified name instead of the ID.

```plantuml
@startuml classes
set namespaceSeparator none
class "Ancestor" as data.clientmodule_test.Ancestor #aliceblue {
attr : str
cls_member
get_value()
set_value(value)
}
class "DoNothing" as data.suppliermodule_test.DoNothing #aliceblue {

}
class "Interface" as data.suppliermodule_test.Interface #aliceblue {
get_value()
set_value(value)
}
class "Specialization" as data.clientmodule_test.Specialization #aliceblue {
TYPE : str
relation
top : str
}
data.clientmodule_test.Specialization --|> data.clientmodule_test.Ancestor
data.clientmodule_test.Ancestor ..|> data.suppliermodule_test.Interface
data.suppliermodule_test.DoNothing --* data.clientmodule_test.Ancestor : cls_member
data.suppliermodule_test.DoNothing --* data.clientmodule_test.Specialization : relation
@enduml
```

The classes appear with just their class name in the diagram, and the aliases are unique.

**Comment by Pierre-Sassoulas** [comment]
Wow, this is neat, I'm pretty sure if plantuml is going to be used a lot !
