### ISSUE TITLE
Pylint errors E1120 and/or E1102 when binding methods

### ISSUE THREAD

**Issue by apbard** [PyCQA/pylint#4588]
I am trying to "enrich" an object by binding some additional methods. 
However, 

- if I use the classical `types.MethodType` approach, pylint gives me a `no-callable` error when using the method.
- if I use the descriptor method `__get__`, pylint gives me a `no-value-for-parameter` error when binding the method.

Is this an expected behaviour? Is there a "right" way to fix this?
I am currently using the `__get__` method and adding `  # pylint: disable=no-value-for-parameter` to make the thing transparent to the users.

### Minimal Example
```python
def _myfunc(self, arg):
    return f"{self.myvar} {arg}"


class myclass:
    def __init__(self):
        self.myvar = "Binding with:"


def get_enriched_object():
    foo = myclass()
    foo.myfunc = types.MethodType(_myfunc, foo)
    foo.myfunc2 = _myfunc.__get__(foo)   # getting the no-value-for-parameter
    return foo


if __name__ == "__main__":
    foo = get_enriched_object()
    print(foo.myfunc("MethodType"))  # getting the not-callable error
    print(foo.myfunc2("__get__"))
```
### Output
```
Binding with: MethodType
Binding with: __get__
```

### pylint result
```
mytest.py:17:18: E1120: No value for argument 'arg' in function call (no-value-for-parameter)
mytest.py:17:18: E1120: No value for argument 'type' in function call (no-value-for-parameter)
mytest.py:23:10: E1102: foo.myfunc is not callable (not-callable)
```
### pylint --version output
```
pylint 2.8.3
```

**Comment by Pierre-Sassoulas** [comment]
This look like something that is too complicated for pylint to understand right now. It might be fixed by creating a brain for "types" (?). Generally if it's complicated for pylint, it's also complicated to understand for humans, so there is an argument to make for another design? You can disable the error until pylint (and astroid in particular) understand this code structure.

**Comment by apbard** [comment]
@Pierre-Sassoulas, ok I'll then use the less common `__get__` approach so that users doesn't have to disable pylint every time

>  so there is an argument to make for another design

is there another way to handle this if you have access only to the instantiated object (beside incapsulating the object and build a complete wrapper of it)?

**Comment by Pierre-Sassoulas** [comment]
Modifying a class at runtime is possible but I personally think it's sacrificing clarity for terseness. I would do a wrapper like you suggested, it's easier to read about a wrapper because you have a concrete type to use in function signatures (so you can go check the wrapper code if you want in o(0) time, and you don't need to do that because even stupid tools can help you autocomplete), whereas you have to read the whole flow of what is happening to the instance to see that the method exists otherwise. (pylint could do that automatically if it had control flow, but I don't think it will have that before a long time). I'm closing the issue as [the label "topic-control-flow"](https://github.com/PyCQA/pylint/issues?q=is%3Aopen+is%3Aissue+label%3Atopic-control-flow) cover it already, but feel free to continue the discussion.
