### ISSUE TITLE
'Line too long' error for py2 style type annotations

### ISSUE THREAD

**Issue by hardikkat24** [PyCQA/pylint#4591]
## Question
I am adding `# type: ignore[error-code]` pragmas to my codebase where I need to suppress MyPy type annotation errors.
For example:
```
constants.LONG_VARIABLE_NAME # type: ignore[attr-defined]
```
Here the linter throws errors like this:
`C:691, 0: Line too long (112/80) `
I don't want these errors for type annotations. How to solve this?

**Comment by Pierre-Sassoulas** [comment]
For pylint there is a proposition to implement #1682, maybe there is a similar ticket for mypy type ignore ? If we start ignoring some constructs because there "justified" to go above the limit this is a slippery slope, so we're not going to do it. The line is really too long. You can make the limit higher or disable the check for the whole project, for the file, the function or... the line 😄.
 
```python
# pylint: disable=line-too-long
constants.LONG_VARIABLE_NAME  # type: ignore[attr-defined]
# pylint: enable=line-too-long
```

**Comment by hardikkat24** [comment]
@Pierre-Sassoulas Thanks a lot! Is there any way I can ignore the comments starting with 'type:'? Or something other than this?

**Comment by Pierre-Sassoulas** [comment]
I don't think there is another way than disabling the warning or changing the limit to a higher number.
