### ISSUE TITLE
Doesn't give a warning if a library is only used once or twice

### ISSUE THREAD

**Issue by xoracle6** [PyCQA/pylint#4706]
Sometimes you only use an import once or twice. Often you can use an already imported library for a specific task which makes extra imports redundant. I think pylint should give a warning when an imported library is seldom being used and/or whether the task could be accomplished with just a single library.

**Comment by Pierre-Sassoulas** [comment]
This seem opinionated so it should definitely be an extension.

**Comment by DanielNoord** [comment]
This seems very difficult to implement: how can we be sure that an already imported library actually allows what the other library does? Perhaps the other library only allows to do this because it itself is already importing the library you are removing?

I'm going to close this as I don't see how we can reasonably implement this without causing numerous false positives. Making an extension to do so should be do-able.
