### ISSUE TITLE
new checker suggestion for unused function under Pylint scope

### ISSUE THREAD

**Issue by orSolocate** [PyCQA/pylint#5773]
### Current problem

I suggest a new checker that will raise a message for any function that is not used under pylint check scope.

some example:

1. if you check Pylint in one file called `func_def.py` with a function definition which isn't called, Pylint will raise a message for it. 
2. If you run Pylint on both `func_def.py` and `func_use.py` on the same run, where `func_use.py` imports `func_def.py` and calls it then a message should not be raised.

### Desired solution

Message Name suggestions: `function-not-called` or  `unused-function` or `uncalled-function`

Message Type: `Warning` / `Refactor`

The message line would be on the function definition.

Message content suggestion:

`The function <function_name> is not called under Pylint scan scope`

I am not sure what suggestion for the user we should have..
 

### Additional context

As far as I checked this checker is not included in Pylint

**Comment by orSolocate** [comment]
I found this issue that somewhat related to my idea #4363, just have to be careful that my this new checker doesn't effect `unused-variable` messages and that it only works on functions and not variables

**Comment by DanielNoord** [comment]
It's pretty common to write functions in separate files and then import them. For example, when you separate your utility functions into a separate file. How would you check for this? Pylint itself would raises this message multiple times.

And what about methods of classes? They are also often used in other files.

**Comment by orSolocate** [comment]
@DanielNoord  I understand what you are saying, for example with a utils package all the instantiations would be external and out of scope, and it is not a rare case.

I suggest then that this checker would be a plugin, then a user who wants to use it can choose to do so. 
A common use case would be a directory with multiple files of a standalone program, where you want all your functions to be called.

**Comment by Pierre-Sassoulas** [comment]
I agree with @DanielNoord here, I don't mind merging opinionated but simple checker as extension (like the one that forbid while loop or ternary condition). But once we add a checker in pylint we must fix the issues with it even if it's an optional extension. So maintenance time and complexity of the checker is something we have to take into account. 

We could add a list of external python package with optional plugins in the documentation to help with discovery though.

**Comment by Pierre-Sassoulas** [comment]
> @Pierre-Sassoulas Is that the reason why we don't have an if-false or assert-false checkers in Pylint that detects unreachable code?

[We have such a check](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/unreachable.html)

Regarding the actual check.
Con:
- It seems there could be a lot of false positive for API (you don't have to call the api yourself except in your tests).
- This is going to be very expansive. IDE do that, but they have a constructed index of the code to be able to do it afaik
- The checker itself is not going to be simple, our pattern is a visitor, so for each function definition we'd have to check the whole code base ? I don't see a simple way to do that with our current framework.

Pro:
- It's hard to detect dead code when your test (and only the tests) are calling it directly, because then coverage is useless and you need to think about it. So this would be a very valuable check
- It's possible to add an option to list the API function that would negate previous point 2

All in all I'm leaning toward closing as won't do. I'm adding a need decision label so we take a decision before 2.16 is out.

**Comment by DanielNoord** [comment]
Let's close this. There is general agreement that this task is probably better done by other tools and does not really fit within the maintenance bandwidth that we currently have.
