### ISSUE TITLE
`pylint` documentation doesn't have page listing all command line options 

### ISSUE THREAD

**Issue by gunungpw** [PyCQA/pylint#6155]
### Question

Hello, I am searching command-line options and examples of how to use it for `pylint` in the documentation but it's very hard and not organized. I want to help document and reorganize commad-line options and maybe config file like `pyproject.toml` and `pylintrc` documentation also can get some love :)

### Documentation for future user

from my experience, `pip` docs have good command line section/topic, maybe `pylint` can copy the way command line options organize in `pip`

[pip commadline docs](https://pip.pypa.io/en/latest/cli/)

### Additional context

I love to help, any advice on where I can see all available options and descriptions in the codebase?

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening this issue that would be awesome.

Concerning ``pyproject.toml`` and ``pylintrc`` there's this existing issue : #3181. But this part is under refactoring @DanielNoord  is removing the need to have top sections right now. Daniel will probably knows the best way to start documenting this as he's refactoring it currently 😄

For the command line options, there's ``--help`` and ``--long-help``. I think it's possible to read it right now and see what isn't clear and need work. If you want to change something you're probably going to need to search for the original string in the whole codebase and modify it because it's integrated in the code.

**Comment by DanielNoord** [comment]
@gunungpw I have created #6346 as a first step towards this. I would love feedback on it!

**Comment by gunungpw** [comment]
@DanielNoord Thank you :), i will try to help
