### ISSUE TITLE
Shorter version of # pylint: disable=...

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/pylint#6349]
### Current problem

PEP8 details limiting all lines to a max of 79 characters.

A pylint disable comment `# pylint: disable=` takes up 18 characters, and that's not yet including the message type(s).  In general, a single-line pylint disable takes up at least 1/3rd of an 80-char line.

For comparison, flake8 uses `# noqa:`, which uses 7 characters.  These 11 saved characters can be valuable.  Especially when running with `black --line-length 79`, where it will wrap a line that was even just one or two characters over.

### Desired solution

I think it would be nice for pylint to support an alternate disabling string:
- `# pylint: disable=` could become `# pyd=` or `# pd=`.
- `# pylint: disable-next=` could become `# pydn=` or `# pdn=`.

### Additional context

I know we can place `pylint` disables onto adjacent lines using `# pylint: disable-next=`, but I prefer using a disable on the same line as the error, when possible.

**Comment by Pierre-Sassoulas** [comment]
This change would have huge ramification, for example black has logic to to not move pylint's disable around. This is just one example of unexpected consequences. Using ``noqa`` could make sense but it would be mixed with other tools disable. For me it seems like a lot of maintenance work for a lot of persons and it would make the disable harder to understand too. I'm putting this in the 2.15 milestone so a decision is taken by then.

**Comment by jamesbraza** [comment]
I came upon https://github.com/psf/black/issues/195 which leads me here https://github.com/psf/black/blob/431bd09e15247431056894bd6444dee7c22893f0/src/black/comments.py#L285.  Yes I do see black considers a `# pylint:` comment a special case.

However, black is still line wrapping for me with `# pylint:` comments, for example:

```python
class Foo:
    @classmethod
    def exact_length(cls, n: bool | str) -> str:  # pylint: disable=invalid-name
        """This 80-char line will not get line wrapped."""

    @classmethod
    def this_will_get_wrapped(cls, n: bool | str) -> str:  # pylint: disable=invalid-name
        """This 89-char line will get line wrapped."""
```

If it will convolute things, then it's totally fine not to accept this, it's just a suggestion of a nice shorthand when space is tight.  For me, I do like `noqa`, but I can see `# noqa:` support easily leading to name collisions with other tools' disables.

**Comment by cdce8p** [comment]
Personally, I do like the the expressiveness of the `pylint: disable=...`. In the past we have deliberately chosen to disallow disable by id and require the message name instead. Let's also consider the cases where you'd want to disable a pylint message
* It's a false positive. In that case, I tend to add the issue link below the `disable-next` comment anyway.
* The check is too strict or I choose to ignore it. Having the full message name (and long comment) really helps bring attention to it. Just so others are aware.

IMO this doesn't need to / shouldn't be changed. If formatting is an issue, it's easy enough to use `pylint: disable-next`.

**Comment by DanielNoord** [comment]
@jamesbraza I'm sympathetic to the idea, but as others said I don't think we will implement this. To add one (last) argument against it:

We have previously looked into only allowing full message names as the pragma scanning is quite performance-heavy. Especially if you consider that it essentially tells `pylint` not to do anything. The processing of all tokens of a file, checking if they are any of our `pragmas`, looking up message IDs, checking if they correspond with an actual message and then finally handling those messages is quite expensive (sadly...).
That's why I explored if we could disallow message IDs as it would eliminate one costly step in the process.

Adding an additional variable to this process is something I don't think we should do.

**Comment by Pierre-Sassoulas** [comment]
I'm closing this as won't fix because to sum up:
- Performance issue if we handle more pylint keywords
- Unforeseen maintenance issue, for pylint dev and for for other dev that interact with pylint one way or another
- Clarity issue in the resulting comment
- Existence of an easy workaround with ``disable-next``
