### ISSUE TITLE
Public interface & versioning

### ISSUE THREAD

**Issue by MrMino** [PyCQA/pylint#6676]
### Question

Does Pylint follow any particular versioning scheme when it comes to adding new warning types?

#1650 would lead me to believe that the project has a notion of a public interface, which should not be broken within minor releases. So, in general:

What (at minimum) is considered to be "public-interface" of pylint?

### Documentation for future user

Somewhere in the documentation, but I don't see any intuitive place for it.

Searching for `pylint versioning` shows an entry in the [FAQ](https://pylint.pycqa.org/en/latest/faq.html#what-kind-of-versioning-system-does-pylint-use), so it might be good to place it somewhere near there.

**Comment by Pierre-Sassoulas** [comment]
[This](https://github.com/PyCQA/pylint/issues/1650#issuecomment-327223970) is still relevant:

> Obviously we do not guarantee that linting output won't change. New checks are added. Old checks are improved to catch more violations (or to avoid false-positives). Sometimes avoiding false positives means that we get some new not-emitted false-negatives. You can also get different results with different version of astroid.

Regarding the second part of the thread, the json output is public API we won't change it in a minor, but we did remove pylint options like ``py3k``. I considered that it was a tool not included in pylint (it was also deactivated for a long time and used for a 'one of' check before migration to python 3).

>  any function, class or module that is underscored is considered private and can change at any time. All other stuff is "public" unless there is an explicit __all__ variable. In that case __all__ is determines what is and what isn't public.

That being said it's true for new code, but we have a lot of small legacy helper functions everywhere that aren't prefixed  and it's not wise to use them like a public API. I don't see myself increasing our maintenance burden threefold by declaring everything public when we document our API later on. The deprecation for 3.0 are already taking a lot of time for pylint's secondary purpose (being an extendable linting lib) to the detriment of the main purpose of pylint (linting code, fast, with few false positives or negatives).

Even if we take care of deprecation the best we can they could inadvertently be modified to fix things...  We also have a thousands little thing to do before being able to release 3.0 so if something make pylint a lot better at the cost of a little breaking change for maintainer... my vote will go in favor of a little breaking change instead of doing all the changes we need to do for 3.0. So if it's not clearly documented, like the custom checker, or ``pylint.lint.Run``... probably don't build anything important on it.

**Comment by MrMino** [comment]
Thanks for fast response. I think I might've under-specified my second question. I wasn't really asking about API, but rather things like CLI, JSON output, config, output stability in general, etc.

To be clear, I have no intentions of advocating for any particular scheme. It's just that I haven't found any information on whether there are parts that you are sure will stay stable on minor releases.

> [This](https://github.com/PyCQA/pylint/issues/1650#issuecomment-327223970) is still relevant:

Can I safely assume that new ones will only be added in minor versions?

> Old checks are improved to catch more violations (or to avoid false-positives)

Is it safe to assume that pinning `pylint` version will also stabilize its output? I see `setup.cfg` has ranges specified for what I believe to be most relevant of dependencies for this question, am I missing something?

@DanielNoord 
>  I would be hesitant to document our API.

The second part of my post was in relation to the versioning scheme question, as in "we use SEMVER or CALVER or COMMONSENSEVER or something else". I'm comming from reproducibility of CI jobs PoV.

**Comment by Pierre-Sassoulas** [comment]
Right now we only fix false positives and crashes in patch release so you can expect less (hopefully, buggy) messages if you set the minor and upgrade to a new patch version. (But say, if you enable useless-suppression it still means you can get a new useless-suppression...). In minor we add checks, remove checks, drop EOL python interpreter, upgrade astroid minor/major versions and fix false negatives. So you can expect a lot more change in output, the main one being new checks.

**Comment by MrMino** [comment]
I think that satisfies the questions I had. Thank you.
