### ISSUE TITLE
Pylint jobs wait a lot start

### ISSUE THREAD

**Issue by leandrogmuller** [PyCQA/pylint#6978]
### Bug description

Hello.
I'm tryng to check many files with -j0 parameter, but the pylint wait all threads get up to begin to check the source.
I have a lot time wait 30 threads to start, so 30 seconds because each thread expend 1 segund to get up.

![process1](https://user-images.githubusercontent.com/3481700/174451346-dad3baf0-61cf-4891-9f33-a95f86f382b1.png)
![process2](https://user-images.githubusercontent.com/3481700/174451349-ca25555f-a182-4252-a1c1-7bed51811d01.png)

### Configuration

```ini
pylint 2.9.6
astroid 2.11.5
Python 3.9.6
```

### Command used

```shell
pylint -j0 xxx.py xxx.py ......
```

### Pylint output

```shell
it's ok
```

### Expected behavior

Start the threads after to get up the process in memory.

### Pylint version

```shell
pylint 2.9.6
astroid 2.11.5
Python 3.9.6
```

### OS / Environment

Windows 11 64

**Comment by Pierre-Sassoulas** [comment]
We have https://github.com/PyCQA/pylint/issues/2525 and https://github.com/PyCQA/pylint/issues/6967 that are probably duplicates.
 
There was a lot of performance improvement since ``2.9.6`` among them https://github.com/PyCQA/pylint/issues/5587, https://github.com/PyCQA/pylint/issues/4814 or https://github.com/PyCQA/pylint/pull/4565. 

Could you try upgrading and see if the performance became acceptable ?

**Comment by leandrogmuller** [comment]
Trying again.
pylint 2.14.3
astroid 2.11.6
Python 3.9.6 

The same problem.

![test2_mon](https://user-images.githubusercontent.com/3481700/174456576-f6a497a1-fc5c-4191-8343-857368001d59.png)
![teste2_monitor](https://user-images.githubusercontent.com/3481700/174456581-b6aea04a-3b3a-4ecc-b3ed-7db4cd6d2f09.png)

**Comment by Pierre-Sassoulas** [comment]
Thanks for checking :) Please follow #2525 for resolution of this issue.
