### ISSUE TITLE
W0402: Deprecated module 'pipes' (deprecated-module)

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/pylint#7130]
### Bug description

```
from pipes import quote
```
That line raises W0402 and recommended `subprocess` module does not have any `quote` method.

### Command used

```shell
pylint example.py
```

### Pylint output

```shell
W0402: Deprecated module 'pipes' (deprecated-module)
```

### Expected behavior

An error message that is 

### Pylint version

```shell
v3.0.0a5
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. We should indeed change the suggestion if it's not accurate But I don't think there's a suggestion in the message ? After a quick search it seems the ``shlex.quote`` is the replacement, could you confirm or suggest a better replacement ?

**Comment by jacobtylerwalls** [comment]
I don't think pylint currently takes responsibility for suggesting replacements for deprecated modules/classes/functions, as there's no expectation of a 1-1 drop-in replacement. (There certainly wasn't for `argparse`!)

**Comment by ssbarnea** [comment]
`shlex.quote` is the right one but I can understand that it could be tricky, especially as people can also define their own deprecations.

Still, for python stdlib deprecations it would be extremely useful if we can provide better errors or even links to docs/wiki pages that can be updated without having to release patches for pylint.

A trying to be too smart and check what was imported is likely to be too hard, maybe just supporting a list of replacements would be enough, something like: "XXX was deprecated as most of its functionality can now be found in A, B, C, ... module(s).".

Knowing that `pipes: [subprocess, shlex]`, should do the trick.

**Comment by DanielNoord** [comment]
I think this would fit very well in the `details.rst` of the message documentation, but shouldn't really be part of the message or message description itself!

**Comment by jacobtylerwalls** [comment]
That page could link to the python documentation for folks not used to going there.

**Comment by Pierre-Sassoulas** [comment]
> details.rst of the message documentation

This is becoming a discussion about a new featuren but I think it would need to be defined in the message directly because ``deprecated-method`` can raise for a number of value that are dynamic (following work from @matusvalo) The data structure is here:

https://github.com/PyCQA/pylint/blob/c1ffa59508841c87e4720c72b2d40fc0ae795622/pylint/checkers/imports.py#L36

Instead of ``(3, 2, 0): {"optparse"},`` we could have ``(3, 2, 0): {("optparse", "argparse",)},`` and the message would change from ``W0402: Deprecated module 'pipes' (deprecated-module)`` to ``W0402: Deprecated module 'optparse' (suggested replacement is 'argparse') (deprecated-module)``, if no replacement can be suggested then we keep the old message.

Probably a good thing and not too hard to do, but I don't know if we need a deprecation period for that.

**Comment by DanielNoord** [comment]
> I don't think pylint currently takes responsibility for suggesting replacements for deprecated modules/classes/functions, as there's no expectation of a 1-1 drop-in replacement. (There certainly wasn't for `argparse`!)

I think this is a good point against suggesting such replacements, I can already see the issues about us suggesting incorrect replacements... 😅

**Comment by matusvalo** [comment]
> > I don't think pylint currently takes responsibility for suggesting replacements for deprecated modules/classes/functions, as there's no expectation of a 1-1 drop-in replacement. (There certainly wasn't for `argparse`!)
> 
> I think this is a good point against suggesting such replacements, I can already see the issues about us suggesting incorrect replacements... 😅

Or there can be multiple possible replacements. This can lead to arguments which is better one. I am slightly -1 about suggesting replacements. I feel that it is beyond pylint main goal.
