### ISSUE TITLE
Suggest ``contextlib.suppress`` instead of ``try`` / ``except`` with ``pass``

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#7201]
Along the same line as #6495 of suggesting standard library functions to produce simpler code:  Please consider suggesting [contextlib.suppress](https://docs.python.org/3/library/contextlib.html#contextlib.suppress), which replaces
```python
try:
    Y # ...
except X:
    pass
```
with
```python
with contextlib.suppress(X):
    Y # ...
```

**Comment by Pierre-Sassoulas** [comment]
@DanielNoord pointed out that performances are worst with ``contextlib`` in this comment : https://github.com/PyCQA/pylint/pull/7215#discussion_r926572609

**Comment by NeilGirdhar** [comment]
@Pierre-Sassoulas Okay, that's fairly convincing.  Either let's not do this, or let's only do this for rare exceptions like `ImportError`.

**Comment by Pierre-Sassoulas** [comment]
Yeah, I agree because it's going to be hard to define what "top level" is. I also have a tendency to highly favor performance when considering a check (being fast is a feature). Maybe in the future if pylint have better default values and suggestion based on user defined criteria this could work for users who really like readability.
