### ISSUE TITLE
pylint is unable to import distutils.version under virtualenv

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#73]
Originally reported by: **Chris Rebert (BitBucket: [cvrebert](http://bitbucket.org/cvrebert), GitHub: @cvrebert?)**

---

Testcase:

```
#!python

#!/usr/bin/env python2.7
import distutils.version
```

Output:

```
#!txt

************* Module foo
foo.py:1: [C0111(missing-docstring), ] Missing module docstring
foo.py:2: [F0401(import-error), ] Unable to import 'distutils.version'
foo.py:2: [E0611(no-name-in-module), ] No name 'version' in module 'distutils'
foo.py:2: [W0611(unused-import), ] Unused import distutils
```

Which doesn't agree with Python itself:

```
#!python

$ python
Python 2.7.3 (default, Apr 10 2013, 06:20:15) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils.version
>>> # no error
```

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/73

**Comment by ygbourhis** [comment]
I still get this 4 years old bug when pylint is installed in a virtual environment... any fix planned?

**Comment by p00j4** [comment]
any work around?

**Comment by nvtkaszpir** [comment]
@p00j4 yeah, just add comment to your code, like this:
```
from distutils.version import LooseVersion  # pylint: disable=no-name-in-module,import-error
```
and this way pylint will ignore two specific errors for that specific line.

**Comment by florent-vial** [comment]
This issue is still (!) here:

python3 --version  # Python 3.4.3
python3 -m virtualenv .venv
source .venv/bin/activate
which python3  # python3 is .venv/bin/python3
python3 -m pip install pylint==1.8.3  # Successfully installed astroid-1.6.2 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 pylint-1.8.3 six-1.11.0 wrapt-1.10.11
echo 'import distutils.version' > dummy.py
python3 -m pylint dummy.py

************* Module dummy
C:  1, 0: Missing module docstring (missing-docstring)
E:  1, 0: No name 'version' in module 'distutils' (no-name-in-module)
E:  1, 0: Unable to import 'distutils.version' (import-error)
W:  1, 0: Unused import distutils.version (unused-import)

--------------------------------------
Your code has been rated at -110.00/10

**Comment by PCManticore** [comment]
Yes, @florent-vial this issue is still (!) here! No one worked on it and no one volunteered to do it, as far as I know. Have you seen how `distutils` looks in a virtualenv? Something like this if you never saw it https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/distutils-init.py. From the point of view of pylint, this `version` module is simply not there. The only way we could potentially understand this is if we could somehow manage to write an astroid brain for `distutils` that patches `version` to be the module outside of the virtualenv, but this sounds hacky, I'm not even sure it's going to work and to be honest I don't even have time to do it.

**Comment by florent-vial** [comment]
Hey thanks for the feedback. I have little insight into the virtualenv internals to say the least, so i am not ready either to dig into this one.
I used the inline # pylint: disable=no-name-in-module,import-error wherever i am using distutils.version, which is an ok workaround after all since i execute code anyway somewhere else.

**Comment by atodorov** [comment]
@PCManticore how about teaching pylint (maybe via extension) to ignore import errors for distutils (if we are inside a virtualenv) ? 

Looking at the history of this issue I am the person with the most commits/references flooding the history. I may as well try to write a patch for it.

**Comment by mattsb42-aws** [comment]
Some anecdata on this: I ran into this issue again recently and updating to Python 3.7 (from 3.6) made it go away.

**Comment by feuGeneA** [comment]
Despite the comment from @mattsb42-aws , I'm encountering this problem with Python 3.7.2.

**Comment by mcallaghan-bsm** [comment]
When's the next pylint release? We are waiting for this fix :)
https://github.com/PyCQA/pylint/releases
