### ISSUE TITLE
Option to suppress import warnings inside __name__ == '__main__' block

### ISSUE THREAD

**Issue by nbastin** [PyCQA/pylint#739]
It would be nice if optionally (or always) we could suppress import warnings (`wrong-position`, mostly), or at least reset the context, within an `if __name__ == '__main__'` block.

**Comment by kernc** [comment]
Should also be able to suppress `invalid-name` errors for non-constant "local" variables defined in these blocks.

**Comment by PCManticore** [comment]
This was probably fixed a while back.

Regarding its potential use for invalid-name, I think those non-constant 'local' variables could be defined inside a function instead of laying around under ``if __name__ == '__main__'`` umbrella (especially if it is a computation, as it seems from their description as non-constant)
