### ISSUE TITLE
Specify python upper version bound 

### ISSUE THREAD

**Issue by kasium** [PyCQA/pylint#7458]
### Current problem

I'm maintain a library which needs to be compatible with python 3.7-3.11 (once released). To check my code quality I use pylint. 
In the later python versions many modules and functions are marked for deprecation. Pylint does a great job to find e.g. imports of such modules.

However, the current deprecated check uses `sys.version_info` to check which modules should be reported as deprecated. Therefore I would need to run pylint with all python versions I support.

### Desired solution

It would be a great feature to specify an upper bound in the configuration. So even if I run pylint with say python 3.8 I get deprecations for python 3.10.

**Comment by Pierre-Sassoulas** [comment]
This is (or at least should be) [``py-version``](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#py-version). Let us know is setting py-version to 3.10 does not work.

**Comment by DanielNoord** [comment]
I don't think that is the correct solution, as `py-version` allows to set the lower bound.

My suggestion is to always run `pylint` with the highest supported version as this offers both speed-ups created in the `stdlib` and better parsing of files due to changes to the internals. You can then use `py-version` to tell `pylint` to also consider older versions.

It is unfeasible to create an upper bound as well as we need info from the `stdlib` modules for many of the checks. With a lower bound we only need to consider stuff that has been removed in between (for example) 3.8 and 3.10. This is a relatively small list as Python takes deprecation somewhat seriously. With an upper bound we would need to consider the full list of changes between 3.8 and 3.10 and add special handling for all new functions, classes, modules, constants, signature changes, etc. The last of "added changes" compared to "removed changes" is much longer and would thus require a heavy maintenance burden for us to support.

**Comment by kasium** [comment]
Thanks for the input. I meant the request as @DanielNoord explained. Due the complexity, I'll close the issue
