### ISSUE TITLE
Check class attribute order

### ISSUE THREAD

**Issue by finswimmer** [PyCQA/pylint#7584]
### Current problem

Enforcing the order of class attributes like private/static/class/normal methods, properties, magic method ... makes reading code more smoothly, as the (re)viewer knows where they can expect to find desired information

### Desired solution

It would be great if `pylint` would have a check for enforcing such an order. Beside a default order, it should be possible to configure it.

### Additional context

This is inspired by the `flake8` plugin [flake8-class-attributes-order](https://pypi.org/project/flake8-class-attributes-order/).

**Comment by cdce8p** [comment]
It would certainly be possible to write an optional checker for it. However, I'm not sure we should do that. What value could `pylint` provide here that isn't already covered by the `flake8` plugin? It would just add additional maintenance load.

**Comment by jacobtylerwalls** [comment]
> What value could pylint provide here that isn't already covered by the flake8 plugin?

I have that question also. I'm also concerned this would need to be an extension as it's as or more opinionated than `black`, and then I wonder about Marc's question even more.

**Comment by Pierre-Sassoulas** [comment]
OP (@finswimmer) commented on discord that he want to use pylint instead of flake8 and that satisfying a single linter is already hard enough. My response was that pylint and flake8 are not incompatible, and that most of the time there's a lot of check that are similar and that fixing pylint also fix flake8 and vice versa. So my advice would be to use both linters. Also it's possible to create a pylint plugin for this if you really want to only use pylint and we could list in our doc.
