### ISSUE TITLE
Make ``consider-using-augmented-assign`` an extension

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#7605]
_I haven't followed the discussion around this check so it might have come up already._

Why was this not implemented as an optional extension?

From what I can tell there is no obvious benefit to using the augmented assignment over the regular one. IMO it just creates a lot of unnecessary noise. Similar checks like the one for assignment expressions are also optional.

_Originally posted by @cdce8p in https://github.com/PyCQA/pylint/issues/7514#issuecomment-1274405286_
      

@cdce8p should this be in CodeStyle? Or just a full extension?

**Comment by cdce8p** [comment]
> @cdce8p should this be in CodeStyle? Or just a full extension?

`consider-using-tuple` and `consider-using-assignment-expr` are part of the `CodeStyle` extension, too. So I think there is an argument for it here.

_A bit off-topic, I think it would be awesome if we could disable all `CodeStyle` checks by default so that users can / must choose which ones they want to enable. Haven't checked if that's already possible._

**Comment by Pierre-Sassoulas** [comment]
> consider-using-tuple and consider-using-assignment-expr are part of the CodeStyle extension, too. So I think there is an argument for it here.

Agreed.

> I think it would be awesome if we could disable all CodeStyle checks by default so that users can / must choose which ones they want to enable. Haven't checked if that's already possible.

Agree with you @cdce8p, we're delaying #3512 but it's one of the most important issue to fix at this point.
