### ISSUE TITLE
py3k suppresses standard pylint messages

### ISSUE THREAD

**Issue by StefanoFioravanzo** [PyCQA/pylint#761]
I noticed that when using `--py3k` option, all standard python2 messages/warning/errors do not appear.
Probably this is a feature but I think it would be great to see both all started messages AND the ones from `--py3k`option.

**Comment by PCManticore** [comment]
This is by design. We decided to do it in this way in order to put emphasis on the checkers that were explicitly targeted for Python 2/3 compatibility. It's unlikely we'll change it to show all the messages, because it will be too verbose and the important messages for Python 2/3 won't be as visible as they are right now.

**Comment by PCManticore** [comment]
One way to do it right now is to call it with ``--py3k --enable=all``

**Comment by StefanoFioravanzo** [comment]
I tried with both `--py3k` and `--enable=all` but it is still showing just py3k messages.

**Comment by PCManticore** [comment]
What pylint version? It works for me with pylint 1.5.2 and astroid 1.4.3, with "--py3k --enable=all".

**Comment by StefanoFioravanzo** [comment]
Ok, I had an older version. Now it works perfectly, thanks.
