### ISSUE TITLE
Calling an attribute before the constructor completes

### ISSUE THREAD

**Issue by e2t** [PyCQA/pylint#7807]
### Current problem

```
class A:
    def __init__(self) -> None:
        self.a = "Hello"
        myfunc(self)
        self.b = "world"

def myfunc(x: A) -> None:
    print(x.a, x.b)

A()
```
This code doesn't work, but linters don't find error (to be expected).
```
Traceback (most recent call last):
  File "C:\Users\eduar\Downloads\1.py", line 12, in <module>
    A()
  File "C:\Users\eduar\Downloads\1.py", line 4, in __init__
    myfunc(self)
  File "C:\Users\eduar\Downloads\1.py", line 9, in myfunc
    print(x.a, x.b)
               ^^^
AttributeError: 'A' object has no attribute 'b'
```

### Desired solution

It would be nice if pylint understood that member "b" does not exist at the stage of calling myfunc().

**Comment by DanielNoord** [comment]
Sadly I don't think we will ever be able to infer this, as there is zero information about the possible caller when we lint the function definition.

Pylint does not have a concept of referenced attributes in a function def and I don't think our system lends us to ever easily implement this. So, linting the call site also isn't feasible.

Therefore, I'm going to close this. Although I'm sympathetic to the request and do think it would be good I don't see how pylint can implement this. Instead of keeping this issue indefinitely I think it's best to close it.
