### ISSUE TITLE
Grammar error in C0209 text

### ISSUE THREAD

**Issue by dnlombard** [PyCQA/pylint#7982]
### Bug description

Grammar error in C0209 text:
C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
Which is used for an unrestrictive clause, 'could be a f-string...' is a restrictive clause.

### Command used

```shell
pylint-3 proggy.py
```

### Pylint output

```shell
$ pylint-3 proggy.py
C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
$
```

### Expected behavior

$ pylint-3 proggy.py
C0209: Formatting a regular string that could be a f-string (consider-using-f-string)
$

### Pylint version

```shell
pylint 2.13.7
astroid 2.11.6
Python 3.10.8 (main, Nov 14 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)]
```

### OS / Environment

Fedora 36

**Comment by mbyrnepr2** [comment]
Thanks @dnlombard. I don't think it's a grammatical error since the use of `which` can be flexible and the meaning of the current message doesn't change if we swap `that` for `which`. 

_In today's usage which and that are both used to introduce restrictive clauses, those which cannot be removed from the context of the sentence, and which is also used to introduce nonrestrictive clauses, those which provide additional information but can be removed without the sentence falling apart._

https://www.merriam-webster.com/words-at-play/when-to-use-that-and-which

**Comment by clavedeluna** [comment]
While using `that` may be more strictly correct, I agree that using either `that` or `which` is practically and meaningfully correct. I don't think this is worth a change.

**Comment by Pierre-Sassoulas** [comment]
Closing in order to avoid churn.
