### ISSUE TITLE
Alert about iterators being assigned to constants

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [PyCQA/pylint#8028]
### Current problem

I'm embarrassed to fess up that I recently wrote something like
```python
MY_FIRST_OTHER_CONSTANT = ('a', 'b', 'c',)
MY_SECOND_OTHER_CONSTANT = ('d', 'e',)
MY_THIRD_OTHER_CONSTANT = ('f', 'g', 'h',)

MY_AGGREGATE_CONSTANT = itertools.chain(
    MY_FIRST_OTHER_CONSTANT,
    MY_SECOND_OTHER_CONSTANT,
    MY_THIRD_OTHER_CONSTANT)
```
This... this did not go well for me or for the folks with whom I share the system.

### Desired solution

`pylint` ought have alerted me that I'd assigned a consumable object (an iterator) to a constant (we can tell it's a constant from its placement at module-scope or class-scope and from [the styling of its name](https://peps.python.org/pep-0008/#constants)).

(There's something of a conversation happening about the wisdom of mutable objects being assigned to constants, but this enhancement request is outside of the scope of that conversation - by "_consumable_ object" I mean something like the iterator in this case, where the object has no means of use that does not mutate it. Such an object is uncontroversially _unusable_ for the value of a constant, yes?)

**Comment by samhansen** [comment]
Without any annotations, is the expectation that pytype will infer immutability by (upper-snake) naming convention?

I do see the type analyzer catching this:

```
MY_FIRST_OTHER_CONSTANT = ('a', 'b', 'c',)
MY_SECOND_OTHER_CONSTANT = ('d', 'e',)
MY_THIRD_OTHER_CONSTANT = ('f', 'g', 'h',)

MY_AGGREGATE_CONSTANT: tuple[str, ...] = itertools.chain(
    MY_FIRST_OTHER_CONSTANT,
    MY_SECOND_OTHER_CONSTANT,
    MY_THIRD_OTHER_CONSTANT)
```

(yes, there's a discussion to be had about variadic tuples, but it's not relevant here). So, if we tell pytype that this should be an immutable tuple of strings, it will catch the error.

```
File "<redacted>", line 7, in <module>: Type annotation for MY_AGGREGATE_CONSTANT does not match type of assignment [annotation-type-mismatch]
  Annotation: Tuple[str, ...]
  Assignment: itertools.chain[str]
```

I agree with you in spirit, however pep-8 is not obligatory. I would think that codifying pep-8 semantics into the type analyzer would go awry for code not adhering to the pep-8 style (which isn't a requirement).

I think the real problem here is that there's nothing to infer. If the value is computed and is required to be a particular type, the type analyzer needs to be told what that type is.

**Comment by DanielNoord** [comment]
I think this is a valuable check, but probably something that should be done as an extension and maintained outside of the main repo. What is and isn't a constant (upper case name, module scope, underscore at start of name, etc.) is very difficult to get right for us as general tool.

Feel free to ping me if somebody ever starts working on this as an extension as I'd love to help out making it. For now I'm closing it.
