### ISSUE TITLE
Reserving blocks of codes for a plugin

### ISSUE THREAD

**Issue by krcb197** [PyCQA/pylint#8152]
### Current problem

I have been using a pylint plugin, [pylint-print](https://pypi.org/project/pylint-print/) to find print statements in code (often left behind from debug). Unfortunately this plugin has stopped working with pylint 2.16 as it uses `W3301` which is assigned to the new nested min/max check. 

There is a bug report against pylint-print, see [Pylint 2.16 has a clashing warning code stops pylint-print working](https://gitlab.com/nwmitchell/pylint-print/-/issues/3).

### Desired solution

There are two solutions to my issue:
1. Adopt pylint-print within pylint, this would solve my immediate issue
2. Allow a 3rd party plugin in to reserve a block of pylint codes so that a this issue stops reoccurring

**Comment by DanielNoord** [comment]
https://github.com/PyCQA/pylint/blob/588c837efc074700d6a49edea8714c7934701012/pylint/checkers/__init__.py#L37

We already reserven the 50-99 range for external plugins. Sadly `pylint-print` apparently didn't follow this and used a number that is reserved for internal use. Sorry about that!

https://github.com/PyCQA/pylint/blob/588c837efc074700d6a49edea8714c7934701012/doc/whatsnew/0/0.x.rst?plain=1#L219-L222
This has been this way since 2011.

**Comment by Pierre-Sassoulas** [comment]
pylint-print functionality can be achieved using the bad-functions option from the deprecated builtin checkers. (Check the doc for `bad-builtin`)
