### ISSUE TITLE
I'm wondering how to deprecate FunctionalTestFile.options because I don't see all of the options in the documentation for pylint

### ISSUE THREAD

**Issue by ollie-iterators** [PyCQA/pylint#8423]
### Question

I am checking out removing FunctionalTestFile.options because it is a TODO for 2.X and the TODO's for 3.X are being removed.

I am having an issue replacing the max_pyver option because I don't see an option for max_pyver. Also, it says that min_pyver is (2, 5) meaning python version 2.5 which should have been changed a long time ago.

### Documentation for future user

I expected this information with the code that should be removed.

### Additional context

**Comment by Pierre-Sassoulas** [comment]
The deprecation and maintenance task are best done by maintainers, we're going to spend more time explaining how to do them than if we were doing them ourselves. If you want to help with pylint development focus an issue that you understand well because it affects you, or something in this list : https://pylint.readthedocs.io/en/latest/development_guide/contributor_guide/contribute.html#finding-something-to-do :)
