### ISSUE TITLE
abstract-method should not be reported unless the class with abstract methods is instantiated

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#843]
abstract-method should not be reported unless the class with abstract methods is instantiated.

**Comment by PCManticore** [comment]
I don't agree with this, the class might not even be used in the project itself, but used as an external API for other libraries. Except that, looking for instantiations of the said class is a hard problem, since the analysis is done at the module level, not across the entire project that gets analyzed. There's also a pattern that we have for detecting when an abstract class gets instantiated, but in that case it is easy to figure this out, since the call site of the instantiation is just there (we don't have to look for it).

**Comment by NeilGirdhar** [comment]
@PCManticore Ah, I see.  Good point.  What's the correct way to mark a class as abstract?

**Comment by NeilGirdhar** [comment]
@PCManticore Yes it's a duplicate of 565.
