### ISSUE TITLE
unused-arguments uses incorrect setting for ignored arguments

### ISSUE THREAD

**Issue by terokinnunen** [PyCQA/pylint#862]
Checker unused-argument uses `dummy-variables-rgx` configuration for ignoring intentionally unused argument name patterns. However, that is intended for variables, not arguments, as documented:

    [VARIABLES]
    # A regular expression matching the name of dummy variables (i.e. expectedly
    # not used).
    dummy-variables-rgx=_$|dummy

Appropriate setting to use would be `ignored-argument-names`.

    [DESIGN]
    # Argument names that match this expression will be ignored. Default to name
    # with leading underscore
    ignored-argument-names=_.*

Example code that should not cause unused-arguments violation with the default `ignored-argument-names`:

    def demo(arg1, _arg2):
        print arg1

Pylint version

    (venv) C:\dev\src>pylint --version
    pylint 1.5.5,
    astroid 1.4.5
    Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by PCManticore** [comment]
Thanks! I guess the purpose of ignored-argument-names was initially for not taking in account those arguments when calculating the proper number of arguments for too-many-arguments check. I admit it is confusing and this is going to be correctly changed in 2.0, since it is a perfect opportunity for breaking the compatibility.
