### ISSUE TITLE
Allow more granularity with "deprecated-method"

### ISSUE THREAD

**Issue by RemiCardona** [PyCQA/pylint#991]
I'm on Python 3.4.2 (shipped with Debian Jessie) and with that version `asyncio.async()` is not yet deprecated in favor of `asyncio.ensure_future()` (which doesn't even exist in that version). So, as far as my projects are concerned, I have the following options:

1. do nothing and ignore this warning
2. disable `deprecated-method` globally
3. litter my code with dozens of `# pylint: disable=deprecated-method`
4. create a compat function somewhere which picks between `async()` and `ensure_future()` and disable the warning there

Option 2 is a clear and resounding no, option 1 breaks our CI builds so stuck with either 3 or 4, neither of which are particularly appealing.

Pylint could provide some mechanisms to help with such an issue:

* only deprecate `async()` when running with Python 3.4.4+ (it looks like adding the patch level in the version tuple should work, untested)
* allow removing one or more items from the deprecated-methods list in pylintrc

Cheers

**Comment by PCManticore** [comment]
Let me know if this fix works for you.

For now, we are using more granular levels, rather than offering a way of removing or adding certain modules. It would be interesting to have it, but I cannot really think of a syntax that would be suitable, since the deprecated modules are grouped by a version in which they started to be deprecated.
